# syntax=docker/dockerfile:1
FROM node:25-alpine AS base

WORKDIR /app

ENV NEXT_PUBLIC_BASE_PATH=/frontend

COPY package.json pnpm-lock.yaml ./
RUN yarn global add pnpm && pnpm i --frozen-lockfile --ignore-scripts

COPY . .

# Expose the port the app runs on
EXPOSE 3000

USER node
CMD ["npm", "run", "dev"]
