# syntax=docker/dockerfile:1
FROM node:25-alpine AS base

WORKDIR /app

ENV NEXT_PUBLIC_BASE_PATH /frontend

COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* ./
RUN \
  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
  elif [ -f package-lock.json ]; then npm ci; \
  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm i --frozen-lockfile; \
  else echo "Lockfile not found." && exit 1; \
  fi

COPY . .

# Expose the port the app runs on
EXPOSE 3000

CMD ["npm", "run", "dev"]
