services:
  proxy:
    image: nginx:latest
    depends_on:
      nutsnode:
        condition: service_started
      ehr:
        condition: service_started
      orchestrator:
        condition: service_started
    ports:
      - "9080:8080"
    volumes:
      - "./config/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro"
  nutsnode:
    image: nutsfoundation/nuts-node:6.0.0
    ports:
      - "9081:8081" # port exposed for loading test data (create DIDs and VCs, requesting access token)
    volumes:
      - "../shared_config/policy/:/nuts/config/policy:ro"
      - "../shared_config/discovery/homemonitoring.json:/nuts/discovery/homemonitoring.json:ro"
    environment:
      - NUTS_VERBOSITY=debug
      - NUTS_STRICTMODE=false
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
      - NUTS_URL=${NUTS_URL}
      - NUTS_DISCOVERY_DEFINITIONS_DIRECTORY=/nuts/discovery/
      - NUTS_DISCOVERY_SERVER_IDS=dev:HomeMonitoring2024
      - NUTS_VDR_DIDMETHODS=web
  nutsadmin:
    image: "nutsfoundation/nuts-admin:main"
    environment:
      - NUTS_NODE_ADDRESS=http://nutsnode:8081
    ports:
      - "1405:1305"
  frontend:
    image: ghcr.io/santeonnl/orca_frontend:main
    # build:
    #  context: ../../../frontend
    #  dockerfile: Dockerfile
     # Make sure to copy the .env.secrets.example and fill in the terminology server credentials for the tx server to work
    env_file:
      - path: ../../../frontend/.env.secrets
        required: false
    ports:
      - "3003:3000"
  orchestrator:
    image: ghcr.io/santeonnl/orca_orchestrator:main
    # build:
    #  context: ../../../orchestrator
    #  dockerfile: Dockerfile
    ports:
      - "8090:8080"
    depends_on:
      fhirstore-healthcheck:
        condition: service_completed_successfully
    environment:
      - ORCA_NUTS_API_URL=http://nutsnode:8081
      - ORCA_NUTS_PUBLIC_URL=${NUTS_URL}
      - ORCA_NUTS_SUBJECT=hospital
      - ORCA_NUTS_DISCOVERYSERVICE=dev:HomeMonitoring2024
      - ORCA_PUBLIC_URL=/orca
      - ORCA_CAREPLANSERVICE_ENABLED=true
      - ORCA_CAREPLANSERVICE_FHIR_URL=http://fhirstore:8080/fhir
      - ORCA_CAREPLANCONTRIBUTOR_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL=${CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL}
      - ORCA_CAREPLANCONTRIBUTOR_FRONTEND_URL=${HOSPITAL_URL}/frontend/enrollment/new
      - ORCA_CAREPLANCONTRIBUTOR_APPLAUNCH_DEMO_ENABLED=true
  fhirstore:
    image: hapiproject/hapi:v7.2.0
    ports:
      - "9090:8080"
    environment:
      - hapi.fhir.fhir_version=R4
  # The HAPI image has no binaries such as curl, so we use the curl image to perform the health check  
  fhirstore-healthcheck:
    image: curlimages/curl:7.87.0
    depends_on:
      - fhirstore
    entrypoint: ["sh", "-c", "echo 'Starting fhirstore healthcheck...'; while ! curl -s -f http://fhirstore:8080/fhir/metadata; do echo 'Waiting for fhirstore to be ready...'; sleep 5; done; echo 'fhirstore is up and running.'"]
    
    # Ensure the container exits successfully after the check
    restart: "no"
  ehr:
    image: ghcr.io/santeonnl/orca_hospitalsimulator:main
    # build:
    #  context: ../../../hospital_simulator
    #  dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fhirstore
    environment:
      ORCA_LOCAL_ORGANIZATION_URA: 4567
      ORCA_LOCAL_ORGANIZATION_NAME: Demo Hospital
      ORCA_PERFORMER_ORGANIZATION_URA: 1234
      ORCA_PERFORMER_ORGANIZATION_NAME: Demo Clinic

#  hospital_sof_adapter:
#    build:
#      context: ../../../smartonfhir_backend_adapter
#      dockerfile: Dockerfile
#    environment:
#      - SOF_BACKEND_ADAPTER_FHIR_BASEURL=https://launch.smarthealthit.org/v/r4/sim/WzQsIiIsIiIsIiIsMCwwLDAsIiIsIiIsIiIsIiIsIiIsIiIsIiIsMCwxXQ/fhir
#      - SOF_BACKEND_ADAPTER_LISTEN_ADDRESS=:8080
#      - SOF_BACKEND_ADAPTER_OAUTH_CLIENT_ID=canbeanything_for_smart_sandbox
#      - SOF_BACKEND_ADAPTER_SIGNINGKEY_FILE=/app/jwk.json
#    ports:
#      - "8080"
#    volumes:
#      - ./config/sof_adapter_signingkey.json:/app/jwk.json:ro
