services:
  proxy:
    image: nginx:latest
    depends_on:
      - nutsnode
      - ehr
    ports:
      - "9080:8080"
    volumes:
      - "./config/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro"
  nutsnode:
    image: nutsfoundation/nuts-node:6.0.0-beta.9
    ports:
      - "9081:8081" # port exposed for loading test data (create DIDs and VCs, requesting access token)
    volumes:
      - "../shared_config/policy/:/nuts/config/policy:ro"
      - "../shared_config/discovery/homemonitoring.json:/nuts/discovery/homemonitoring.json:ro"
    environment:
      - NUTS_VERBOSITY=debug
      - NUTS_STRICTMODE=false
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
      - NUTS_URL=${NUTS_URL}
      - NUTS_DISCOVERY_DEFINITIONS_DIRECTORY=/nuts/discovery/
      - NUTS_VDR_DIDMETHODS=web
  nutsadmin:
    image: "nutsfoundation/nuts-admin:main"
    environment:
      - NUTS_NODE_ADDRESS=http://nutsnode:8081
    ports:
      - "1405:1305"
  frontend:
    image: ghcr.io/santeonnl/orca_frontend:main
    # build:
    #  context: ../../../frontend
    #  dockerfile: Dockerfile
     # Make sure to copy the .env.secrets.example and fill in the terminology server credentials for the tx server to work
    env_file:
      - path: ../../../frontend/.env.secrets
        required: false
    ports:
      - "3003:3000"
  orchestrator:
    image: ghcr.io/santeonnl/orca_orchestrator:main
    # build:
    #  context: ../../../orchestrator
    #  dockerfile: Dockerfile
    ports:
      - "8090:8080"
    environment:
      - ORCA_NUTS_API_URL=http://nutsnode:8081
      - ORCA_NUTS_PUBLIC_URL=${NUTS_URL}
      - ORCA_NUTS_DID=${HOSPITAL_DID}
      - ORCA_PUBLIC_URL=/orca
      - ORCA_CAREPLANCONTRIBUTOR_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL=${CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL}
      - ORCA_CAREPLANCONTRIBUTOR_FRONTEND_URL=${HOSPITAL_URL}/frontend/enrollment/new
      - ORCA_APPLAUNCH_DEMO_ENABLED=true
  fhirstore:
    image: hapiproject/hapi:v7.2.0
    ports:
      - "9090:8080"
    environment:
      - hapi.fhir.fhir_version=R4
  ehr:
    image: ghcr.io/santeonnl/orca_hospitalsimulator:main
    # build:
    #  context: ../../../hospital_simulator
    #  dockerfile: Dockerfile
    ports:
      - "3001:3000"
    depends_on:
      - fhirstore
#  hospital_sof_adapter:
#    build:
#      context: ../../../smartonfhir_backend_adapter
#      dockerfile: Dockerfile
#    environment:
#      - SOF_BACKEND_ADAPTER_FHIR_BASEURL=https://launch.smarthealthit.org/v/r4/sim/WzQsIiIsIiIsIiIsMCwwLDAsIiIsIiIsIiIsIiIsIiIsIiIsIiIsMCwxXQ/fhir
#      - SOF_BACKEND_ADAPTER_LISTEN_ADDRESS=:8080
#      - SOF_BACKEND_ADAPTER_OAUTH_CLIENT_ID=canbeanything_for_smart_sandbox
#      - SOF_BACKEND_ADAPTER_SIGNINGKEY_FILE=/app/jwk.json
#    ports:
#      - "8080"
#    volumes:
#      - ./config/sof_adapter_signingkey.json:/app/jwk.json:ro
