apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "nuts.fullname" . }}
spec:
  selfSigned: {}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nuts.fullname" . }}-ca
spec:
  isCA: true
  commonName: {{ include "nuts.fullname" . }}-ca
  secretName: tls-{{ include "nuts.fullname" . }}-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: {{ include "nuts.fullname" . }}
    kind: Issuer
    group: cert-manager.io

---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "nuts.fullname" . }}-ca-issuer
spec:
  ca:
    secretName: tls-{{ include "nuts.fullname" . }}-ca

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nuts.fullname" . }}-internal
spec:
  secretName: tls-cert-{{ include "nuts.fullname" . }}-internal
  issuerRef:
    kind: Issuer
    name: {{ include "nuts.fullname" . }}-ca-issuer
  dnsNames: [{{ include "nuts.fullname" . }}]

{{- if .Values.gateway.enabled }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "nuts.fullname" . }}
spec:
  secretName: tls-cert-{{ include "nuts.fullname" . }}
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-dns
  dnsNames:
    {{ .Values.gateway.node.hosts | toYaml | nindent 4 }}
{{- end }}
