{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "nuts.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    {{ .Values.gateway.node.hosts | toYaml | nindent 4 }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - name: {{ include "nuts.fullname" . }}
          port: {{ .Values.service.port }}
    - matches:
        - path:
            type: PathPrefix
            value: /internal
      backendRefs:
        - name: {{ include "nuts.fullname" . }}
          port: 8081
{{- end }}
