apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "nuts.fullname" . }}
  labels:
    {{- include "nuts.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "nuts.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "nuts.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nuts.serviceAccountName" . }}
      {{- with .Values.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
          {{- if .Values.tls.enabled }}
            - name: NUTS_TLS_CERTFILE
              value: /nuts/certs/tls.crt
            - name: NUTS_TLS_CERTKEYFILE
              value: /nuts/certs/tls.key
            - name: NUTS_TLS_TRUSTSTOREFILE
              value: /nuts/certs/ca.crt
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "nuts.fullname" . }}-config
          ports:
            - name: internal
              containerPort: 8081
              protocol: TCP
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          {{- with .Values.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          volumeMounts:
            {{- if .Values.persistence.enabled }}
            - name: data
              mountPath: /nuts/data
            {{- end }}
            - name: policy
              mountPath: /nuts/config/policy
            - name: discovery
              mountPath: /nuts/discovery
            {{- if .Values.tls.enabled }}
            - name: tls
              mountPath: /nuts/certs
            {{- end }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      volumes:
        {{- if .Values.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ include "nuts.fullname" . }}-data
        {{- end }}
        - name: policy
          configMap:
            name: {{ include "nuts.fullname" . }}-policy
        - name: discovery
          configMap:
            name: {{ include "nuts.fullname" . }}-discovery
        {{- if .Values.tls.enabled }}
        - name: tls
          secret:
            secretName: tls-cert-{{ include "nuts.fullname" . }}-internal
        {{- end }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
