apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fhir.fullname" . }}-config
data:
  {{- toYaml .Values.config | nindent 2 }}
  {{- if .Values.configExtra }}
  {{- toYaml .Values.configExtra | nindent 2 }}
  {{- end }}


