package coolfhir

// Code generated by go generate; DO NOT EDIT.

import (
	"fmt"
	"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"
)

func ResourceType(resource interface{}) string {
	switch resource.(type) {
	case *fhir.Account:
		return "Account"
	case fhir.Account:
		return "Account"
	case *fhir.ActivityDefinition:
		return "ActivityDefinition"
	case fhir.ActivityDefinition:
		return "ActivityDefinition"
	case *fhir.AdverseEvent:
		return "AdverseEvent"
	case fhir.AdverseEvent:
		return "AdverseEvent"
	case *fhir.AllergyIntolerance:
		return "AllergyIntolerance"
	case fhir.AllergyIntolerance:
		return "AllergyIntolerance"
	case *fhir.Appointment:
		return "Appointment"
	case fhir.Appointment:
		return "Appointment"
	case *fhir.AppointmentResponse:
		return "AppointmentResponse"
	case fhir.AppointmentResponse:
		return "AppointmentResponse"
	case *fhir.AuditEvent:
		return "AuditEvent"
	case fhir.AuditEvent:
		return "AuditEvent"
	case *fhir.Basic:
		return "Basic"
	case fhir.Basic:
		return "Basic"
	case *fhir.Binary:
		return "Binary"
	case fhir.Binary:
		return "Binary"
	case *fhir.BiologicallyDerivedProduct:
		return "BiologicallyDerivedProduct"
	case fhir.BiologicallyDerivedProduct:
		return "BiologicallyDerivedProduct"
	case *fhir.BodyStructure:
		return "BodyStructure"
	case fhir.BodyStructure:
		return "BodyStructure"
	case *fhir.Bundle:
		return "Bundle"
	case fhir.Bundle:
		return "Bundle"
	case *fhir.CapabilityStatement:
		return "CapabilityStatement"
	case fhir.CapabilityStatement:
		return "CapabilityStatement"
	case *fhir.CarePlan:
		return "CarePlan"
	case fhir.CarePlan:
		return "CarePlan"
	case *fhir.CareTeam:
		return "CareTeam"
	case fhir.CareTeam:
		return "CareTeam"
	case *fhir.CatalogEntry:
		return "CatalogEntry"
	case fhir.CatalogEntry:
		return "CatalogEntry"
	case *fhir.ChargeItem:
		return "ChargeItem"
	case fhir.ChargeItem:
		return "ChargeItem"
	case *fhir.ChargeItemDefinition:
		return "ChargeItemDefinition"
	case fhir.ChargeItemDefinition:
		return "ChargeItemDefinition"
	case *fhir.Claim:
		return "Claim"
	case fhir.Claim:
		return "Claim"
	case *fhir.ClaimResponse:
		return "ClaimResponse"
	case fhir.ClaimResponse:
		return "ClaimResponse"
	case *fhir.ClinicalImpression:
		return "ClinicalImpression"
	case fhir.ClinicalImpression:
		return "ClinicalImpression"
	case *fhir.CodeSystem:
		return "CodeSystem"
	case fhir.CodeSystem:
		return "CodeSystem"
	case *fhir.Communication:
		return "Communication"
	case fhir.Communication:
		return "Communication"
	case *fhir.CommunicationRequest:
		return "CommunicationRequest"
	case fhir.CommunicationRequest:
		return "CommunicationRequest"
	case *fhir.CompartmentDefinition:
		return "CompartmentDefinition"
	case fhir.CompartmentDefinition:
		return "CompartmentDefinition"
	case *fhir.Composition:
		return "Composition"
	case fhir.Composition:
		return "Composition"
	case *fhir.ConceptMap:
		return "ConceptMap"
	case fhir.ConceptMap:
		return "ConceptMap"
	case *fhir.Condition:
		return "Condition"
	case fhir.Condition:
		return "Condition"
	case *fhir.Consent:
		return "Consent"
	case fhir.Consent:
		return "Consent"
	case *fhir.Contract:
		return "Contract"
	case fhir.Contract:
		return "Contract"
	case *fhir.Coverage:
		return "Coverage"
	case fhir.Coverage:
		return "Coverage"
	case *fhir.CoverageEligibilityRequest:
		return "CoverageEligibilityRequest"
	case fhir.CoverageEligibilityRequest:
		return "CoverageEligibilityRequest"
	case *fhir.CoverageEligibilityResponse:
		return "CoverageEligibilityResponse"
	case fhir.CoverageEligibilityResponse:
		return "CoverageEligibilityResponse"
	case *fhir.DetectedIssue:
		return "DetectedIssue"
	case fhir.DetectedIssue:
		return "DetectedIssue"
	case *fhir.Device:
		return "Device"
	case fhir.Device:
		return "Device"
	case *fhir.DeviceDefinition:
		return "DeviceDefinition"
	case fhir.DeviceDefinition:
		return "DeviceDefinition"
	case *fhir.DeviceMetric:
		return "DeviceMetric"
	case fhir.DeviceMetric:
		return "DeviceMetric"
	case *fhir.DeviceRequest:
		return "DeviceRequest"
	case fhir.DeviceRequest:
		return "DeviceRequest"
	case *fhir.DeviceUseStatement:
		return "DeviceUseStatement"
	case fhir.DeviceUseStatement:
		return "DeviceUseStatement"
	case *fhir.DiagnosticReport:
		return "DiagnosticReport"
	case fhir.DiagnosticReport:
		return "DiagnosticReport"
	case *fhir.DocumentManifest:
		return "DocumentManifest"
	case fhir.DocumentManifest:
		return "DocumentManifest"
	case *fhir.DocumentReference:
		return "DocumentReference"
	case fhir.DocumentReference:
		return "DocumentReference"
	case *fhir.EffectEvidenceSynthesis:
		return "EffectEvidenceSynthesis"
	case fhir.EffectEvidenceSynthesis:
		return "EffectEvidenceSynthesis"
	case *fhir.Encounter:
		return "Encounter"
	case fhir.Encounter:
		return "Encounter"
	case *fhir.Endpoint:
		return "Endpoint"
	case fhir.Endpoint:
		return "Endpoint"
	case *fhir.EnrollmentRequest:
		return "EnrollmentRequest"
	case fhir.EnrollmentRequest:
		return "EnrollmentRequest"
	case *fhir.EnrollmentResponse:
		return "EnrollmentResponse"
	case fhir.EnrollmentResponse:
		return "EnrollmentResponse"
	case *fhir.EpisodeOfCare:
		return "EpisodeOfCare"
	case fhir.EpisodeOfCare:
		return "EpisodeOfCare"
	case *fhir.EventDefinition:
		return "EventDefinition"
	case fhir.EventDefinition:
		return "EventDefinition"
	case *fhir.Evidence:
		return "Evidence"
	case fhir.Evidence:
		return "Evidence"
	case *fhir.EvidenceVariable:
		return "EvidenceVariable"
	case fhir.EvidenceVariable:
		return "EvidenceVariable"
	case *fhir.ExampleScenario:
		return "ExampleScenario"
	case fhir.ExampleScenario:
		return "ExampleScenario"
	case *fhir.ExplanationOfBenefit:
		return "ExplanationOfBenefit"
	case fhir.ExplanationOfBenefit:
		return "ExplanationOfBenefit"
	case *fhir.FamilyMemberHistory:
		return "FamilyMemberHistory"
	case fhir.FamilyMemberHistory:
		return "FamilyMemberHistory"
	case *fhir.Flag:
		return "Flag"
	case fhir.Flag:
		return "Flag"
	case *fhir.Goal:
		return "Goal"
	case fhir.Goal:
		return "Goal"
	case *fhir.GraphDefinition:
		return "GraphDefinition"
	case fhir.GraphDefinition:
		return "GraphDefinition"
	case *fhir.Group:
		return "Group"
	case fhir.Group:
		return "Group"
	case *fhir.GuidanceResponse:
		return "GuidanceResponse"
	case fhir.GuidanceResponse:
		return "GuidanceResponse"
	case *fhir.HealthcareService:
		return "HealthcareService"
	case fhir.HealthcareService:
		return "HealthcareService"
	case *fhir.ImagingStudy:
		return "ImagingStudy"
	case fhir.ImagingStudy:
		return "ImagingStudy"
	case *fhir.Immunization:
		return "Immunization"
	case fhir.Immunization:
		return "Immunization"
	case *fhir.ImmunizationEvaluation:
		return "ImmunizationEvaluation"
	case fhir.ImmunizationEvaluation:
		return "ImmunizationEvaluation"
	case *fhir.ImmunizationRecommendation:
		return "ImmunizationRecommendation"
	case fhir.ImmunizationRecommendation:
		return "ImmunizationRecommendation"
	case *fhir.ImplementationGuide:
		return "ImplementationGuide"
	case fhir.ImplementationGuide:
		return "ImplementationGuide"
	case *fhir.InsurancePlan:
		return "InsurancePlan"
	case fhir.InsurancePlan:
		return "InsurancePlan"
	case *fhir.Invoice:
		return "Invoice"
	case fhir.Invoice:
		return "Invoice"
	case *fhir.Library:
		return "Library"
	case fhir.Library:
		return "Library"
	case *fhir.Linkage:
		return "Linkage"
	case fhir.Linkage:
		return "Linkage"
	case *fhir.List:
		return "List"
	case fhir.List:
		return "List"
	case *fhir.Location:
		return "Location"
	case fhir.Location:
		return "Location"
	case *fhir.Measure:
		return "Measure"
	case fhir.Measure:
		return "Measure"
	case *fhir.MeasureReport:
		return "MeasureReport"
	case fhir.MeasureReport:
		return "MeasureReport"
	case *fhir.Media:
		return "Media"
	case fhir.Media:
		return "Media"
	case *fhir.Medication:
		return "Medication"
	case fhir.Medication:
		return "Medication"
	case *fhir.MedicationAdministration:
		return "MedicationAdministration"
	case fhir.MedicationAdministration:
		return "MedicationAdministration"
	case *fhir.MedicationDispense:
		return "MedicationDispense"
	case fhir.MedicationDispense:
		return "MedicationDispense"
	case *fhir.MedicationKnowledge:
		return "MedicationKnowledge"
	case fhir.MedicationKnowledge:
		return "MedicationKnowledge"
	case *fhir.MedicationRequest:
		return "MedicationRequest"
	case fhir.MedicationRequest:
		return "MedicationRequest"
	case *fhir.MedicationStatement:
		return "MedicationStatement"
	case fhir.MedicationStatement:
		return "MedicationStatement"
	case *fhir.MedicinalProduct:
		return "MedicinalProduct"
	case fhir.MedicinalProduct:
		return "MedicinalProduct"
	case *fhir.MedicinalProductAuthorization:
		return "MedicinalProductAuthorization"
	case fhir.MedicinalProductAuthorization:
		return "MedicinalProductAuthorization"
	case *fhir.MedicinalProductContraindication:
		return "MedicinalProductContraindication"
	case fhir.MedicinalProductContraindication:
		return "MedicinalProductContraindication"
	case *fhir.MedicinalProductIndication:
		return "MedicinalProductIndication"
	case fhir.MedicinalProductIndication:
		return "MedicinalProductIndication"
	case *fhir.MedicinalProductIngredient:
		return "MedicinalProductIngredient"
	case fhir.MedicinalProductIngredient:
		return "MedicinalProductIngredient"
	case *fhir.MedicinalProductInteraction:
		return "MedicinalProductInteraction"
	case fhir.MedicinalProductInteraction:
		return "MedicinalProductInteraction"
	case *fhir.MedicinalProductManufactured:
		return "MedicinalProductManufactured"
	case fhir.MedicinalProductManufactured:
		return "MedicinalProductManufactured"
	case *fhir.MedicinalProductPackaged:
		return "MedicinalProductPackaged"
	case fhir.MedicinalProductPackaged:
		return "MedicinalProductPackaged"
	case *fhir.MedicinalProductPharmaceutical:
		return "MedicinalProductPharmaceutical"
	case fhir.MedicinalProductPharmaceutical:
		return "MedicinalProductPharmaceutical"
	case *fhir.MedicinalProductUndesirableEffect:
		return "MedicinalProductUndesirableEffect"
	case fhir.MedicinalProductUndesirableEffect:
		return "MedicinalProductUndesirableEffect"
	case *fhir.MessageDefinition:
		return "MessageDefinition"
	case fhir.MessageDefinition:
		return "MessageDefinition"
	case *fhir.MessageHeader:
		return "MessageHeader"
	case fhir.MessageHeader:
		return "MessageHeader"
	case *fhir.MolecularSequence:
		return "MolecularSequence"
	case fhir.MolecularSequence:
		return "MolecularSequence"
	case *fhir.NamingSystem:
		return "NamingSystem"
	case fhir.NamingSystem:
		return "NamingSystem"
	case *fhir.NutritionOrder:
		return "NutritionOrder"
	case fhir.NutritionOrder:
		return "NutritionOrder"
	case *fhir.Observation:
		return "Observation"
	case fhir.Observation:
		return "Observation"
	case *fhir.ObservationDefinition:
		return "ObservationDefinition"
	case fhir.ObservationDefinition:
		return "ObservationDefinition"
	case *fhir.OperationDefinition:
		return "OperationDefinition"
	case fhir.OperationDefinition:
		return "OperationDefinition"
	case *fhir.OperationOutcome:
		return "OperationOutcome"
	case fhir.OperationOutcome:
		return "OperationOutcome"
	case *fhir.Organization:
		return "Organization"
	case fhir.Organization:
		return "Organization"
	case *fhir.OrganizationAffiliation:
		return "OrganizationAffiliation"
	case fhir.OrganizationAffiliation:
		return "OrganizationAffiliation"
	case *fhir.Parameters:
		return "Parameters"
	case fhir.Parameters:
		return "Parameters"
	case *fhir.Patient:
		return "Patient"
	case fhir.Patient:
		return "Patient"
	case *fhir.PaymentNotice:
		return "PaymentNotice"
	case fhir.PaymentNotice:
		return "PaymentNotice"
	case *fhir.PaymentReconciliation:
		return "PaymentReconciliation"
	case fhir.PaymentReconciliation:
		return "PaymentReconciliation"
	case *fhir.Person:
		return "Person"
	case fhir.Person:
		return "Person"
	case *fhir.PlanDefinition:
		return "PlanDefinition"
	case fhir.PlanDefinition:
		return "PlanDefinition"
	case *fhir.Practitioner:
		return "Practitioner"
	case fhir.Practitioner:
		return "Practitioner"
	case *fhir.PractitionerRole:
		return "PractitionerRole"
	case fhir.PractitionerRole:
		return "PractitionerRole"
	case *fhir.Procedure:
		return "Procedure"
	case fhir.Procedure:
		return "Procedure"
	case *fhir.Provenance:
		return "Provenance"
	case fhir.Provenance:
		return "Provenance"
	case *fhir.Questionnaire:
		return "Questionnaire"
	case fhir.Questionnaire:
		return "Questionnaire"
	case *fhir.QuestionnaireResponse:
		return "QuestionnaireResponse"
	case fhir.QuestionnaireResponse:
		return "QuestionnaireResponse"
	case *fhir.RelatedPerson:
		return "RelatedPerson"
	case fhir.RelatedPerson:
		return "RelatedPerson"
	case *fhir.RequestGroup:
		return "RequestGroup"
	case fhir.RequestGroup:
		return "RequestGroup"
	case *fhir.ResearchDefinition:
		return "ResearchDefinition"
	case fhir.ResearchDefinition:
		return "ResearchDefinition"
	case *fhir.ResearchElementDefinition:
		return "ResearchElementDefinition"
	case fhir.ResearchElementDefinition:
		return "ResearchElementDefinition"
	case *fhir.ResearchStudy:
		return "ResearchStudy"
	case fhir.ResearchStudy:
		return "ResearchStudy"
	case *fhir.ResearchSubject:
		return "ResearchSubject"
	case fhir.ResearchSubject:
		return "ResearchSubject"
	case *fhir.RiskAssessment:
		return "RiskAssessment"
	case fhir.RiskAssessment:
		return "RiskAssessment"
	case *fhir.RiskEvidenceSynthesis:
		return "RiskEvidenceSynthesis"
	case fhir.RiskEvidenceSynthesis:
		return "RiskEvidenceSynthesis"
	case *fhir.Schedule:
		return "Schedule"
	case fhir.Schedule:
		return "Schedule"
	case *fhir.SearchParameter:
		return "SearchParameter"
	case fhir.SearchParameter:
		return "SearchParameter"
	case *fhir.ServiceRequest:
		return "ServiceRequest"
	case fhir.ServiceRequest:
		return "ServiceRequest"
	case *fhir.Slot:
		return "Slot"
	case fhir.Slot:
		return "Slot"
	case *fhir.Specimen:
		return "Specimen"
	case fhir.Specimen:
		return "Specimen"
	case *fhir.SpecimenDefinition:
		return "SpecimenDefinition"
	case fhir.SpecimenDefinition:
		return "SpecimenDefinition"
	case *fhir.StructureDefinition:
		return "StructureDefinition"
	case fhir.StructureDefinition:
		return "StructureDefinition"
	case *fhir.StructureMap:
		return "StructureMap"
	case fhir.StructureMap:
		return "StructureMap"
	case *fhir.Subscription:
		return "Subscription"
	case fhir.Subscription:
		return "Subscription"
	case *fhir.Substance:
		return "Substance"
	case fhir.Substance:
		return "Substance"
	case *fhir.SubstanceNucleicAcid:
		return "SubstanceNucleicAcid"
	case fhir.SubstanceNucleicAcid:
		return "SubstanceNucleicAcid"
	case *fhir.SubstancePolymer:
		return "SubstancePolymer"
	case fhir.SubstancePolymer:
		return "SubstancePolymer"
	case *fhir.SubstanceProtein:
		return "SubstanceProtein"
	case fhir.SubstanceProtein:
		return "SubstanceProtein"
	case *fhir.SubstanceReferenceInformation:
		return "SubstanceReferenceInformation"
	case fhir.SubstanceReferenceInformation:
		return "SubstanceReferenceInformation"
	case *fhir.SubstanceSourceMaterial:
		return "SubstanceSourceMaterial"
	case fhir.SubstanceSourceMaterial:
		return "SubstanceSourceMaterial"
	case *fhir.SubstanceSpecification:
		return "SubstanceSpecification"
	case fhir.SubstanceSpecification:
		return "SubstanceSpecification"
	case *fhir.SupplyDelivery:
		return "SupplyDelivery"
	case fhir.SupplyDelivery:
		return "SupplyDelivery"
	case *fhir.SupplyRequest:
		return "SupplyRequest"
	case fhir.SupplyRequest:
		return "SupplyRequest"
	case *fhir.Task:
		return "Task"
	case fhir.Task:
		return "Task"
	case *fhir.TerminologyCapabilities:
		return "TerminologyCapabilities"
	case fhir.TerminologyCapabilities:
		return "TerminologyCapabilities"
	case *fhir.TestReport:
		return "TestReport"
	case fhir.TestReport:
		return "TestReport"
	case *fhir.TestScript:
		return "TestScript"
	case fhir.TestScript:
		return "TestScript"
	case *fhir.ValueSet:
		return "ValueSet"
	case fhir.ValueSet:
		return "ValueSet"
	case *fhir.VerificationResult:
		return "VerificationResult"
	case fhir.VerificationResult:
		return "VerificationResult"
	case *fhir.VisionPrescription:
		return "VisionPrescription"
	case fhir.VisionPrescription:
		return "VisionPrescription"
	default:
		return ""
	}
}

func ResourceID(resource interface{}) *string {
	switch resource.(type) {
	case *fhir.Account:
		return (*resource.(*fhir.Account)).Id
	case fhir.Account:
		return (resource.(fhir.Account)).Id
	case *fhir.ActivityDefinition:
		return (*resource.(*fhir.ActivityDefinition)).Id
	case fhir.ActivityDefinition:
		return (resource.(fhir.ActivityDefinition)).Id
	case *fhir.AdverseEvent:
		return (*resource.(*fhir.AdverseEvent)).Id
	case fhir.AdverseEvent:
		return (resource.(fhir.AdverseEvent)).Id
	case *fhir.AllergyIntolerance:
		return (*resource.(*fhir.AllergyIntolerance)).Id
	case fhir.AllergyIntolerance:
		return (resource.(fhir.AllergyIntolerance)).Id
	case *fhir.Appointment:
		return (*resource.(*fhir.Appointment)).Id
	case fhir.Appointment:
		return (resource.(fhir.Appointment)).Id
	case *fhir.AppointmentResponse:
		return (*resource.(*fhir.AppointmentResponse)).Id
	case fhir.AppointmentResponse:
		return (resource.(fhir.AppointmentResponse)).Id
	case *fhir.AuditEvent:
		return (*resource.(*fhir.AuditEvent)).Id
	case fhir.AuditEvent:
		return (resource.(fhir.AuditEvent)).Id
	case *fhir.Basic:
		return (*resource.(*fhir.Basic)).Id
	case fhir.Basic:
		return (resource.(fhir.Basic)).Id
	case *fhir.Binary:
		return (*resource.(*fhir.Binary)).Id
	case fhir.Binary:
		return (resource.(fhir.Binary)).Id
	case *fhir.BiologicallyDerivedProduct:
		return (*resource.(*fhir.BiologicallyDerivedProduct)).Id
	case fhir.BiologicallyDerivedProduct:
		return (resource.(fhir.BiologicallyDerivedProduct)).Id
	case *fhir.BodyStructure:
		return (*resource.(*fhir.BodyStructure)).Id
	case fhir.BodyStructure:
		return (resource.(fhir.BodyStructure)).Id
	case *fhir.Bundle:
		return (*resource.(*fhir.Bundle)).Id
	case fhir.Bundle:
		return (resource.(fhir.Bundle)).Id
	case *fhir.CapabilityStatement:
		return (*resource.(*fhir.CapabilityStatement)).Id
	case fhir.CapabilityStatement:
		return (resource.(fhir.CapabilityStatement)).Id
	case *fhir.CarePlan:
		return (*resource.(*fhir.CarePlan)).Id
	case fhir.CarePlan:
		return (resource.(fhir.CarePlan)).Id
	case *fhir.CareTeam:
		return (*resource.(*fhir.CareTeam)).Id
	case fhir.CareTeam:
		return (resource.(fhir.CareTeam)).Id
	case *fhir.CatalogEntry:
		return (*resource.(*fhir.CatalogEntry)).Id
	case fhir.CatalogEntry:
		return (resource.(fhir.CatalogEntry)).Id
	case *fhir.ChargeItem:
		return (*resource.(*fhir.ChargeItem)).Id
	case fhir.ChargeItem:
		return (resource.(fhir.ChargeItem)).Id
	case *fhir.ChargeItemDefinition:
		return (*resource.(*fhir.ChargeItemDefinition)).Id
	case fhir.ChargeItemDefinition:
		return (resource.(fhir.ChargeItemDefinition)).Id
	case *fhir.Claim:
		return (*resource.(*fhir.Claim)).Id
	case fhir.Claim:
		return (resource.(fhir.Claim)).Id
	case *fhir.ClaimResponse:
		return (*resource.(*fhir.ClaimResponse)).Id
	case fhir.ClaimResponse:
		return (resource.(fhir.ClaimResponse)).Id
	case *fhir.ClinicalImpression:
		return (*resource.(*fhir.ClinicalImpression)).Id
	case fhir.ClinicalImpression:
		return (resource.(fhir.ClinicalImpression)).Id
	case *fhir.CodeSystem:
		return (*resource.(*fhir.CodeSystem)).Id
	case fhir.CodeSystem:
		return (resource.(fhir.CodeSystem)).Id
	case *fhir.Communication:
		return (*resource.(*fhir.Communication)).Id
	case fhir.Communication:
		return (resource.(fhir.Communication)).Id
	case *fhir.CommunicationRequest:
		return (*resource.(*fhir.CommunicationRequest)).Id
	case fhir.CommunicationRequest:
		return (resource.(fhir.CommunicationRequest)).Id
	case *fhir.CompartmentDefinition:
		return (*resource.(*fhir.CompartmentDefinition)).Id
	case fhir.CompartmentDefinition:
		return (resource.(fhir.CompartmentDefinition)).Id
	case *fhir.Composition:
		return (*resource.(*fhir.Composition)).Id
	case fhir.Composition:
		return (resource.(fhir.Composition)).Id
	case *fhir.ConceptMap:
		return (*resource.(*fhir.ConceptMap)).Id
	case fhir.ConceptMap:
		return (resource.(fhir.ConceptMap)).Id
	case *fhir.Condition:
		return (*resource.(*fhir.Condition)).Id
	case fhir.Condition:
		return (resource.(fhir.Condition)).Id
	case *fhir.Consent:
		return (*resource.(*fhir.Consent)).Id
	case fhir.Consent:
		return (resource.(fhir.Consent)).Id
	case *fhir.Contract:
		return (*resource.(*fhir.Contract)).Id
	case fhir.Contract:
		return (resource.(fhir.Contract)).Id
	case *fhir.Coverage:
		return (*resource.(*fhir.Coverage)).Id
	case fhir.Coverage:
		return (resource.(fhir.Coverage)).Id
	case *fhir.CoverageEligibilityRequest:
		return (*resource.(*fhir.CoverageEligibilityRequest)).Id
	case fhir.CoverageEligibilityRequest:
		return (resource.(fhir.CoverageEligibilityRequest)).Id
	case *fhir.CoverageEligibilityResponse:
		return (*resource.(*fhir.CoverageEligibilityResponse)).Id
	case fhir.CoverageEligibilityResponse:
		return (resource.(fhir.CoverageEligibilityResponse)).Id
	case *fhir.DetectedIssue:
		return (*resource.(*fhir.DetectedIssue)).Id
	case fhir.DetectedIssue:
		return (resource.(fhir.DetectedIssue)).Id
	case *fhir.Device:
		return (*resource.(*fhir.Device)).Id
	case fhir.Device:
		return (resource.(fhir.Device)).Id
	case *fhir.DeviceDefinition:
		return (*resource.(*fhir.DeviceDefinition)).Id
	case fhir.DeviceDefinition:
		return (resource.(fhir.DeviceDefinition)).Id
	case *fhir.DeviceMetric:
		return (*resource.(*fhir.DeviceMetric)).Id
	case fhir.DeviceMetric:
		return (resource.(fhir.DeviceMetric)).Id
	case *fhir.DeviceRequest:
		return (*resource.(*fhir.DeviceRequest)).Id
	case fhir.DeviceRequest:
		return (resource.(fhir.DeviceRequest)).Id
	case *fhir.DeviceUseStatement:
		return (*resource.(*fhir.DeviceUseStatement)).Id
	case fhir.DeviceUseStatement:
		return (resource.(fhir.DeviceUseStatement)).Id
	case *fhir.DiagnosticReport:
		return (*resource.(*fhir.DiagnosticReport)).Id
	case fhir.DiagnosticReport:
		return (resource.(fhir.DiagnosticReport)).Id
	case *fhir.DocumentManifest:
		return (*resource.(*fhir.DocumentManifest)).Id
	case fhir.DocumentManifest:
		return (resource.(fhir.DocumentManifest)).Id
	case *fhir.DocumentReference:
		return (*resource.(*fhir.DocumentReference)).Id
	case fhir.DocumentReference:
		return (resource.(fhir.DocumentReference)).Id
	case *fhir.EffectEvidenceSynthesis:
		return (*resource.(*fhir.EffectEvidenceSynthesis)).Id
	case fhir.EffectEvidenceSynthesis:
		return (resource.(fhir.EffectEvidenceSynthesis)).Id
	case *fhir.Encounter:
		return (*resource.(*fhir.Encounter)).Id
	case fhir.Encounter:
		return (resource.(fhir.Encounter)).Id
	case *fhir.Endpoint:
		return (*resource.(*fhir.Endpoint)).Id
	case fhir.Endpoint:
		return (resource.(fhir.Endpoint)).Id
	case *fhir.EnrollmentRequest:
		return (*resource.(*fhir.EnrollmentRequest)).Id
	case fhir.EnrollmentRequest:
		return (resource.(fhir.EnrollmentRequest)).Id
	case *fhir.EnrollmentResponse:
		return (*resource.(*fhir.EnrollmentResponse)).Id
	case fhir.EnrollmentResponse:
		return (resource.(fhir.EnrollmentResponse)).Id
	case *fhir.EpisodeOfCare:
		return (*resource.(*fhir.EpisodeOfCare)).Id
	case fhir.EpisodeOfCare:
		return (resource.(fhir.EpisodeOfCare)).Id
	case *fhir.EventDefinition:
		return (*resource.(*fhir.EventDefinition)).Id
	case fhir.EventDefinition:
		return (resource.(fhir.EventDefinition)).Id
	case *fhir.Evidence:
		return (*resource.(*fhir.Evidence)).Id
	case fhir.Evidence:
		return (resource.(fhir.Evidence)).Id
	case *fhir.EvidenceVariable:
		return (*resource.(*fhir.EvidenceVariable)).Id
	case fhir.EvidenceVariable:
		return (resource.(fhir.EvidenceVariable)).Id
	case *fhir.ExampleScenario:
		return (*resource.(*fhir.ExampleScenario)).Id
	case fhir.ExampleScenario:
		return (resource.(fhir.ExampleScenario)).Id
	case *fhir.ExplanationOfBenefit:
		return (*resource.(*fhir.ExplanationOfBenefit)).Id
	case fhir.ExplanationOfBenefit:
		return (resource.(fhir.ExplanationOfBenefit)).Id
	case *fhir.FamilyMemberHistory:
		return (*resource.(*fhir.FamilyMemberHistory)).Id
	case fhir.FamilyMemberHistory:
		return (resource.(fhir.FamilyMemberHistory)).Id
	case *fhir.Flag:
		return (*resource.(*fhir.Flag)).Id
	case fhir.Flag:
		return (resource.(fhir.Flag)).Id
	case *fhir.Goal:
		return (*resource.(*fhir.Goal)).Id
	case fhir.Goal:
		return (resource.(fhir.Goal)).Id
	case *fhir.GraphDefinition:
		return (*resource.(*fhir.GraphDefinition)).Id
	case fhir.GraphDefinition:
		return (resource.(fhir.GraphDefinition)).Id
	case *fhir.Group:
		return (*resource.(*fhir.Group)).Id
	case fhir.Group:
		return (resource.(fhir.Group)).Id
	case *fhir.GuidanceResponse:
		return (*resource.(*fhir.GuidanceResponse)).Id
	case fhir.GuidanceResponse:
		return (resource.(fhir.GuidanceResponse)).Id
	case *fhir.HealthcareService:
		return (*resource.(*fhir.HealthcareService)).Id
	case fhir.HealthcareService:
		return (resource.(fhir.HealthcareService)).Id
	case *fhir.ImagingStudy:
		return (*resource.(*fhir.ImagingStudy)).Id
	case fhir.ImagingStudy:
		return (resource.(fhir.ImagingStudy)).Id
	case *fhir.Immunization:
		return (*resource.(*fhir.Immunization)).Id
	case fhir.Immunization:
		return (resource.(fhir.Immunization)).Id
	case *fhir.ImmunizationEvaluation:
		return (*resource.(*fhir.ImmunizationEvaluation)).Id
	case fhir.ImmunizationEvaluation:
		return (resource.(fhir.ImmunizationEvaluation)).Id
	case *fhir.ImmunizationRecommendation:
		return (*resource.(*fhir.ImmunizationRecommendation)).Id
	case fhir.ImmunizationRecommendation:
		return (resource.(fhir.ImmunizationRecommendation)).Id
	case *fhir.ImplementationGuide:
		return (*resource.(*fhir.ImplementationGuide)).Id
	case fhir.ImplementationGuide:
		return (resource.(fhir.ImplementationGuide)).Id
	case *fhir.InsurancePlan:
		return (*resource.(*fhir.InsurancePlan)).Id
	case fhir.InsurancePlan:
		return (resource.(fhir.InsurancePlan)).Id
	case *fhir.Invoice:
		return (*resource.(*fhir.Invoice)).Id
	case fhir.Invoice:
		return (resource.(fhir.Invoice)).Id
	case *fhir.Library:
		return (*resource.(*fhir.Library)).Id
	case fhir.Library:
		return (resource.(fhir.Library)).Id
	case *fhir.Linkage:
		return (*resource.(*fhir.Linkage)).Id
	case fhir.Linkage:
		return (resource.(fhir.Linkage)).Id
	case *fhir.List:
		return (*resource.(*fhir.List)).Id
	case fhir.List:
		return (resource.(fhir.List)).Id
	case *fhir.Location:
		return (*resource.(*fhir.Location)).Id
	case fhir.Location:
		return (resource.(fhir.Location)).Id
	case *fhir.Measure:
		return (*resource.(*fhir.Measure)).Id
	case fhir.Measure:
		return (resource.(fhir.Measure)).Id
	case *fhir.MeasureReport:
		return (*resource.(*fhir.MeasureReport)).Id
	case fhir.MeasureReport:
		return (resource.(fhir.MeasureReport)).Id
	case *fhir.Media:
		return (*resource.(*fhir.Media)).Id
	case fhir.Media:
		return (resource.(fhir.Media)).Id
	case *fhir.Medication:
		return (*resource.(*fhir.Medication)).Id
	case fhir.Medication:
		return (resource.(fhir.Medication)).Id
	case *fhir.MedicationAdministration:
		return (*resource.(*fhir.MedicationAdministration)).Id
	case fhir.MedicationAdministration:
		return (resource.(fhir.MedicationAdministration)).Id
	case *fhir.MedicationDispense:
		return (*resource.(*fhir.MedicationDispense)).Id
	case fhir.MedicationDispense:
		return (resource.(fhir.MedicationDispense)).Id
	case *fhir.MedicationKnowledge:
		return (*resource.(*fhir.MedicationKnowledge)).Id
	case fhir.MedicationKnowledge:
		return (resource.(fhir.MedicationKnowledge)).Id
	case *fhir.MedicationRequest:
		return (*resource.(*fhir.MedicationRequest)).Id
	case fhir.MedicationRequest:
		return (resource.(fhir.MedicationRequest)).Id
	case *fhir.MedicationStatement:
		return (*resource.(*fhir.MedicationStatement)).Id
	case fhir.MedicationStatement:
		return (resource.(fhir.MedicationStatement)).Id
	case *fhir.MedicinalProduct:
		return (*resource.(*fhir.MedicinalProduct)).Id
	case fhir.MedicinalProduct:
		return (resource.(fhir.MedicinalProduct)).Id
	case *fhir.MedicinalProductAuthorization:
		return (*resource.(*fhir.MedicinalProductAuthorization)).Id
	case fhir.MedicinalProductAuthorization:
		return (resource.(fhir.MedicinalProductAuthorization)).Id
	case *fhir.MedicinalProductContraindication:
		return (*resource.(*fhir.MedicinalProductContraindication)).Id
	case fhir.MedicinalProductContraindication:
		return (resource.(fhir.MedicinalProductContraindication)).Id
	case *fhir.MedicinalProductIndication:
		return (*resource.(*fhir.MedicinalProductIndication)).Id
	case fhir.MedicinalProductIndication:
		return (resource.(fhir.MedicinalProductIndication)).Id
	case *fhir.MedicinalProductIngredient:
		return (*resource.(*fhir.MedicinalProductIngredient)).Id
	case fhir.MedicinalProductIngredient:
		return (resource.(fhir.MedicinalProductIngredient)).Id
	case *fhir.MedicinalProductInteraction:
		return (*resource.(*fhir.MedicinalProductInteraction)).Id
	case fhir.MedicinalProductInteraction:
		return (resource.(fhir.MedicinalProductInteraction)).Id
	case *fhir.MedicinalProductManufactured:
		return (*resource.(*fhir.MedicinalProductManufactured)).Id
	case fhir.MedicinalProductManufactured:
		return (resource.(fhir.MedicinalProductManufactured)).Id
	case *fhir.MedicinalProductPackaged:
		return (*resource.(*fhir.MedicinalProductPackaged)).Id
	case fhir.MedicinalProductPackaged:
		return (resource.(fhir.MedicinalProductPackaged)).Id
	case *fhir.MedicinalProductPharmaceutical:
		return (*resource.(*fhir.MedicinalProductPharmaceutical)).Id
	case fhir.MedicinalProductPharmaceutical:
		return (resource.(fhir.MedicinalProductPharmaceutical)).Id
	case *fhir.MedicinalProductUndesirableEffect:
		return (*resource.(*fhir.MedicinalProductUndesirableEffect)).Id
	case fhir.MedicinalProductUndesirableEffect:
		return (resource.(fhir.MedicinalProductUndesirableEffect)).Id
	case *fhir.MessageDefinition:
		return (*resource.(*fhir.MessageDefinition)).Id
	case fhir.MessageDefinition:
		return (resource.(fhir.MessageDefinition)).Id
	case *fhir.MessageHeader:
		return (*resource.(*fhir.MessageHeader)).Id
	case fhir.MessageHeader:
		return (resource.(fhir.MessageHeader)).Id
	case *fhir.MolecularSequence:
		return (*resource.(*fhir.MolecularSequence)).Id
	case fhir.MolecularSequence:
		return (resource.(fhir.MolecularSequence)).Id
	case *fhir.NamingSystem:
		return (*resource.(*fhir.NamingSystem)).Id
	case fhir.NamingSystem:
		return (resource.(fhir.NamingSystem)).Id
	case *fhir.NutritionOrder:
		return (*resource.(*fhir.NutritionOrder)).Id
	case fhir.NutritionOrder:
		return (resource.(fhir.NutritionOrder)).Id
	case *fhir.Observation:
		return (*resource.(*fhir.Observation)).Id
	case fhir.Observation:
		return (resource.(fhir.Observation)).Id
	case *fhir.ObservationDefinition:
		return (*resource.(*fhir.ObservationDefinition)).Id
	case fhir.ObservationDefinition:
		return (resource.(fhir.ObservationDefinition)).Id
	case *fhir.OperationDefinition:
		return (*resource.(*fhir.OperationDefinition)).Id
	case fhir.OperationDefinition:
		return (resource.(fhir.OperationDefinition)).Id
	case *fhir.OperationOutcome:
		return (*resource.(*fhir.OperationOutcome)).Id
	case fhir.OperationOutcome:
		return (resource.(fhir.OperationOutcome)).Id
	case *fhir.Organization:
		return (*resource.(*fhir.Organization)).Id
	case fhir.Organization:
		return (resource.(fhir.Organization)).Id
	case *fhir.OrganizationAffiliation:
		return (*resource.(*fhir.OrganizationAffiliation)).Id
	case fhir.OrganizationAffiliation:
		return (resource.(fhir.OrganizationAffiliation)).Id
	case *fhir.Parameters:
		return (*resource.(*fhir.Parameters)).Id
	case fhir.Parameters:
		return (resource.(fhir.Parameters)).Id
	case *fhir.Patient:
		return (*resource.(*fhir.Patient)).Id
	case fhir.Patient:
		return (resource.(fhir.Patient)).Id
	case *fhir.PaymentNotice:
		return (*resource.(*fhir.PaymentNotice)).Id
	case fhir.PaymentNotice:
		return (resource.(fhir.PaymentNotice)).Id
	case *fhir.PaymentReconciliation:
		return (*resource.(*fhir.PaymentReconciliation)).Id
	case fhir.PaymentReconciliation:
		return (resource.(fhir.PaymentReconciliation)).Id
	case *fhir.Person:
		return (*resource.(*fhir.Person)).Id
	case fhir.Person:
		return (resource.(fhir.Person)).Id
	case *fhir.PlanDefinition:
		return (*resource.(*fhir.PlanDefinition)).Id
	case fhir.PlanDefinition:
		return (resource.(fhir.PlanDefinition)).Id
	case *fhir.Practitioner:
		return (*resource.(*fhir.Practitioner)).Id
	case fhir.Practitioner:
		return (resource.(fhir.Practitioner)).Id
	case *fhir.PractitionerRole:
		return (*resource.(*fhir.PractitionerRole)).Id
	case fhir.PractitionerRole:
		return (resource.(fhir.PractitionerRole)).Id
	case *fhir.Procedure:
		return (*resource.(*fhir.Procedure)).Id
	case fhir.Procedure:
		return (resource.(fhir.Procedure)).Id
	case *fhir.Provenance:
		return (*resource.(*fhir.Provenance)).Id
	case fhir.Provenance:
		return (resource.(fhir.Provenance)).Id
	case *fhir.Questionnaire:
		return (*resource.(*fhir.Questionnaire)).Id
	case fhir.Questionnaire:
		return (resource.(fhir.Questionnaire)).Id
	case *fhir.QuestionnaireResponse:
		return (*resource.(*fhir.QuestionnaireResponse)).Id
	case fhir.QuestionnaireResponse:
		return (resource.(fhir.QuestionnaireResponse)).Id
	case *fhir.RelatedPerson:
		return (*resource.(*fhir.RelatedPerson)).Id
	case fhir.RelatedPerson:
		return (resource.(fhir.RelatedPerson)).Id
	case *fhir.RequestGroup:
		return (*resource.(*fhir.RequestGroup)).Id
	case fhir.RequestGroup:
		return (resource.(fhir.RequestGroup)).Id
	case *fhir.ResearchDefinition:
		return (*resource.(*fhir.ResearchDefinition)).Id
	case fhir.ResearchDefinition:
		return (resource.(fhir.ResearchDefinition)).Id
	case *fhir.ResearchElementDefinition:
		return (*resource.(*fhir.ResearchElementDefinition)).Id
	case fhir.ResearchElementDefinition:
		return (resource.(fhir.ResearchElementDefinition)).Id
	case *fhir.ResearchStudy:
		return (*resource.(*fhir.ResearchStudy)).Id
	case fhir.ResearchStudy:
		return (resource.(fhir.ResearchStudy)).Id
	case *fhir.ResearchSubject:
		return (*resource.(*fhir.ResearchSubject)).Id
	case fhir.ResearchSubject:
		return (resource.(fhir.ResearchSubject)).Id
	case *fhir.RiskAssessment:
		return (*resource.(*fhir.RiskAssessment)).Id
	case fhir.RiskAssessment:
		return (resource.(fhir.RiskAssessment)).Id
	case *fhir.RiskEvidenceSynthesis:
		return (*resource.(*fhir.RiskEvidenceSynthesis)).Id
	case fhir.RiskEvidenceSynthesis:
		return (resource.(fhir.RiskEvidenceSynthesis)).Id
	case *fhir.Schedule:
		return (*resource.(*fhir.Schedule)).Id
	case fhir.Schedule:
		return (resource.(fhir.Schedule)).Id
	case *fhir.SearchParameter:
		return (*resource.(*fhir.SearchParameter)).Id
	case fhir.SearchParameter:
		return (resource.(fhir.SearchParameter)).Id
	case *fhir.ServiceRequest:
		return (*resource.(*fhir.ServiceRequest)).Id
	case fhir.ServiceRequest:
		return (resource.(fhir.ServiceRequest)).Id
	case *fhir.Slot:
		return (*resource.(*fhir.Slot)).Id
	case fhir.Slot:
		return (resource.(fhir.Slot)).Id
	case *fhir.Specimen:
		return (*resource.(*fhir.Specimen)).Id
	case fhir.Specimen:
		return (resource.(fhir.Specimen)).Id
	case *fhir.SpecimenDefinition:
		return (*resource.(*fhir.SpecimenDefinition)).Id
	case fhir.SpecimenDefinition:
		return (resource.(fhir.SpecimenDefinition)).Id
	case *fhir.StructureDefinition:
		return (*resource.(*fhir.StructureDefinition)).Id
	case fhir.StructureDefinition:
		return (resource.(fhir.StructureDefinition)).Id
	case *fhir.StructureMap:
		return (*resource.(*fhir.StructureMap)).Id
	case fhir.StructureMap:
		return (resource.(fhir.StructureMap)).Id
	case *fhir.Subscription:
		return (*resource.(*fhir.Subscription)).Id
	case fhir.Subscription:
		return (resource.(fhir.Subscription)).Id
	case *fhir.Substance:
		return (*resource.(*fhir.Substance)).Id
	case fhir.Substance:
		return (resource.(fhir.Substance)).Id
	case *fhir.SubstanceNucleicAcid:
		return (*resource.(*fhir.SubstanceNucleicAcid)).Id
	case fhir.SubstanceNucleicAcid:
		return (resource.(fhir.SubstanceNucleicAcid)).Id
	case *fhir.SubstancePolymer:
		return (*resource.(*fhir.SubstancePolymer)).Id
	case fhir.SubstancePolymer:
		return (resource.(fhir.SubstancePolymer)).Id
	case *fhir.SubstanceProtein:
		return (*resource.(*fhir.SubstanceProtein)).Id
	case fhir.SubstanceProtein:
		return (resource.(fhir.SubstanceProtein)).Id
	case *fhir.SubstanceReferenceInformation:
		return (*resource.(*fhir.SubstanceReferenceInformation)).Id
	case fhir.SubstanceReferenceInformation:
		return (resource.(fhir.SubstanceReferenceInformation)).Id
	case *fhir.SubstanceSourceMaterial:
		return (*resource.(*fhir.SubstanceSourceMaterial)).Id
	case fhir.SubstanceSourceMaterial:
		return (resource.(fhir.SubstanceSourceMaterial)).Id
	case *fhir.SubstanceSpecification:
		return (*resource.(*fhir.SubstanceSpecification)).Id
	case fhir.SubstanceSpecification:
		return (resource.(fhir.SubstanceSpecification)).Id
	case *fhir.SupplyDelivery:
		return (*resource.(*fhir.SupplyDelivery)).Id
	case fhir.SupplyDelivery:
		return (resource.(fhir.SupplyDelivery)).Id
	case *fhir.SupplyRequest:
		return (*resource.(*fhir.SupplyRequest)).Id
	case fhir.SupplyRequest:
		return (resource.(fhir.SupplyRequest)).Id
	case *fhir.Task:
		return (*resource.(*fhir.Task)).Id
	case fhir.Task:
		return (resource.(fhir.Task)).Id
	case *fhir.TerminologyCapabilities:
		return (*resource.(*fhir.TerminologyCapabilities)).Id
	case fhir.TerminologyCapabilities:
		return (resource.(fhir.TerminologyCapabilities)).Id
	case *fhir.TestReport:
		return (*resource.(*fhir.TestReport)).Id
	case fhir.TestReport:
		return (resource.(fhir.TestReport)).Id
	case *fhir.TestScript:
		return (*resource.(*fhir.TestScript)).Id
	case fhir.TestScript:
		return (resource.(fhir.TestScript)).Id
	case *fhir.ValueSet:
		return (*resource.(*fhir.ValueSet)).Id
	case fhir.ValueSet:
		return (resource.(fhir.ValueSet)).Id
	case *fhir.VerificationResult:
		return (*resource.(*fhir.VerificationResult)).Id
	case fhir.VerificationResult:
		return (resource.(fhir.VerificationResult)).Id
	case *fhir.VisionPrescription:
		return (*resource.(*fhir.VisionPrescription)).Id
	case fhir.VisionPrescription:
		return (resource.(fhir.VisionPrescription)).Id
	default:
		panic("ResourceID called with non-FHIR resource: " + fmt.Sprintf("%T", resource))
	}
}

func SetSource(resource interface{}, source *string) {
	switch resource.(type) {
	case *fhir.Account:
		meta := resource.(*fhir.Account).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Account).Meta = meta
		}
		meta.Source = source
	case *fhir.ActivityDefinition:
		meta := resource.(*fhir.ActivityDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ActivityDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.AdverseEvent:
		meta := resource.(*fhir.AdverseEvent).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.AdverseEvent).Meta = meta
		}
		meta.Source = source
	case *fhir.AllergyIntolerance:
		meta := resource.(*fhir.AllergyIntolerance).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.AllergyIntolerance).Meta = meta
		}
		meta.Source = source
	case *fhir.Appointment:
		meta := resource.(*fhir.Appointment).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Appointment).Meta = meta
		}
		meta.Source = source
	case *fhir.AppointmentResponse:
		meta := resource.(*fhir.AppointmentResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.AppointmentResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.AuditEvent:
		meta := resource.(*fhir.AuditEvent).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.AuditEvent).Meta = meta
		}
		meta.Source = source
	case *fhir.Basic:
		meta := resource.(*fhir.Basic).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Basic).Meta = meta
		}
		meta.Source = source
	case *fhir.Binary:
		meta := resource.(*fhir.Binary).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Binary).Meta = meta
		}
		meta.Source = source
	case *fhir.BiologicallyDerivedProduct:
		meta := resource.(*fhir.BiologicallyDerivedProduct).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.BiologicallyDerivedProduct).Meta = meta
		}
		meta.Source = source
	case *fhir.BodyStructure:
		meta := resource.(*fhir.BodyStructure).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.BodyStructure).Meta = meta
		}
		meta.Source = source
	case *fhir.Bundle:
		meta := resource.(*fhir.Bundle).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Bundle).Meta = meta
		}
		meta.Source = source
	case *fhir.CapabilityStatement:
		meta := resource.(*fhir.CapabilityStatement).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CapabilityStatement).Meta = meta
		}
		meta.Source = source
	case *fhir.CarePlan:
		meta := resource.(*fhir.CarePlan).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CarePlan).Meta = meta
		}
		meta.Source = source
	case *fhir.CareTeam:
		meta := resource.(*fhir.CareTeam).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CareTeam).Meta = meta
		}
		meta.Source = source
	case *fhir.CatalogEntry:
		meta := resource.(*fhir.CatalogEntry).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CatalogEntry).Meta = meta
		}
		meta.Source = source
	case *fhir.ChargeItem:
		meta := resource.(*fhir.ChargeItem).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ChargeItem).Meta = meta
		}
		meta.Source = source
	case *fhir.ChargeItemDefinition:
		meta := resource.(*fhir.ChargeItemDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ChargeItemDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.Claim:
		meta := resource.(*fhir.Claim).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Claim).Meta = meta
		}
		meta.Source = source
	case *fhir.ClaimResponse:
		meta := resource.(*fhir.ClaimResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ClaimResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.ClinicalImpression:
		meta := resource.(*fhir.ClinicalImpression).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ClinicalImpression).Meta = meta
		}
		meta.Source = source
	case *fhir.CodeSystem:
		meta := resource.(*fhir.CodeSystem).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CodeSystem).Meta = meta
		}
		meta.Source = source
	case *fhir.Communication:
		meta := resource.(*fhir.Communication).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Communication).Meta = meta
		}
		meta.Source = source
	case *fhir.CommunicationRequest:
		meta := resource.(*fhir.CommunicationRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CommunicationRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.CompartmentDefinition:
		meta := resource.(*fhir.CompartmentDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CompartmentDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.Composition:
		meta := resource.(*fhir.Composition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Composition).Meta = meta
		}
		meta.Source = source
	case *fhir.ConceptMap:
		meta := resource.(*fhir.ConceptMap).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ConceptMap).Meta = meta
		}
		meta.Source = source
	case *fhir.Condition:
		meta := resource.(*fhir.Condition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Condition).Meta = meta
		}
		meta.Source = source
	case *fhir.Consent:
		meta := resource.(*fhir.Consent).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Consent).Meta = meta
		}
		meta.Source = source
	case *fhir.Contract:
		meta := resource.(*fhir.Contract).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Contract).Meta = meta
		}
		meta.Source = source
	case *fhir.Coverage:
		meta := resource.(*fhir.Coverage).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Coverage).Meta = meta
		}
		meta.Source = source
	case *fhir.CoverageEligibilityRequest:
		meta := resource.(*fhir.CoverageEligibilityRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CoverageEligibilityRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.CoverageEligibilityResponse:
		meta := resource.(*fhir.CoverageEligibilityResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.CoverageEligibilityResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.DetectedIssue:
		meta := resource.(*fhir.DetectedIssue).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DetectedIssue).Meta = meta
		}
		meta.Source = source
	case *fhir.Device:
		meta := resource.(*fhir.Device).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Device).Meta = meta
		}
		meta.Source = source
	case *fhir.DeviceDefinition:
		meta := resource.(*fhir.DeviceDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DeviceDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.DeviceMetric:
		meta := resource.(*fhir.DeviceMetric).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DeviceMetric).Meta = meta
		}
		meta.Source = source
	case *fhir.DeviceRequest:
		meta := resource.(*fhir.DeviceRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DeviceRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.DeviceUseStatement:
		meta := resource.(*fhir.DeviceUseStatement).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DeviceUseStatement).Meta = meta
		}
		meta.Source = source
	case *fhir.DiagnosticReport:
		meta := resource.(*fhir.DiagnosticReport).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DiagnosticReport).Meta = meta
		}
		meta.Source = source
	case *fhir.DocumentManifest:
		meta := resource.(*fhir.DocumentManifest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DocumentManifest).Meta = meta
		}
		meta.Source = source
	case *fhir.DocumentReference:
		meta := resource.(*fhir.DocumentReference).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.DocumentReference).Meta = meta
		}
		meta.Source = source
	case *fhir.EffectEvidenceSynthesis:
		meta := resource.(*fhir.EffectEvidenceSynthesis).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EffectEvidenceSynthesis).Meta = meta
		}
		meta.Source = source
	case *fhir.Encounter:
		meta := resource.(*fhir.Encounter).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Encounter).Meta = meta
		}
		meta.Source = source
	case *fhir.Endpoint:
		meta := resource.(*fhir.Endpoint).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Endpoint).Meta = meta
		}
		meta.Source = source
	case *fhir.EnrollmentRequest:
		meta := resource.(*fhir.EnrollmentRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EnrollmentRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.EnrollmentResponse:
		meta := resource.(*fhir.EnrollmentResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EnrollmentResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.EpisodeOfCare:
		meta := resource.(*fhir.EpisodeOfCare).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EpisodeOfCare).Meta = meta
		}
		meta.Source = source
	case *fhir.EventDefinition:
		meta := resource.(*fhir.EventDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EventDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.Evidence:
		meta := resource.(*fhir.Evidence).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Evidence).Meta = meta
		}
		meta.Source = source
	case *fhir.EvidenceVariable:
		meta := resource.(*fhir.EvidenceVariable).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.EvidenceVariable).Meta = meta
		}
		meta.Source = source
	case *fhir.ExampleScenario:
		meta := resource.(*fhir.ExampleScenario).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ExampleScenario).Meta = meta
		}
		meta.Source = source
	case *fhir.ExplanationOfBenefit:
		meta := resource.(*fhir.ExplanationOfBenefit).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ExplanationOfBenefit).Meta = meta
		}
		meta.Source = source
	case *fhir.FamilyMemberHistory:
		meta := resource.(*fhir.FamilyMemberHistory).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.FamilyMemberHistory).Meta = meta
		}
		meta.Source = source
	case *fhir.Flag:
		meta := resource.(*fhir.Flag).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Flag).Meta = meta
		}
		meta.Source = source
	case *fhir.Goal:
		meta := resource.(*fhir.Goal).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Goal).Meta = meta
		}
		meta.Source = source
	case *fhir.GraphDefinition:
		meta := resource.(*fhir.GraphDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.GraphDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.Group:
		meta := resource.(*fhir.Group).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Group).Meta = meta
		}
		meta.Source = source
	case *fhir.GuidanceResponse:
		meta := resource.(*fhir.GuidanceResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.GuidanceResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.HealthcareService:
		meta := resource.(*fhir.HealthcareService).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.HealthcareService).Meta = meta
		}
		meta.Source = source
	case *fhir.ImagingStudy:
		meta := resource.(*fhir.ImagingStudy).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ImagingStudy).Meta = meta
		}
		meta.Source = source
	case *fhir.Immunization:
		meta := resource.(*fhir.Immunization).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Immunization).Meta = meta
		}
		meta.Source = source
	case *fhir.ImmunizationEvaluation:
		meta := resource.(*fhir.ImmunizationEvaluation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ImmunizationEvaluation).Meta = meta
		}
		meta.Source = source
	case *fhir.ImmunizationRecommendation:
		meta := resource.(*fhir.ImmunizationRecommendation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ImmunizationRecommendation).Meta = meta
		}
		meta.Source = source
	case *fhir.ImplementationGuide:
		meta := resource.(*fhir.ImplementationGuide).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ImplementationGuide).Meta = meta
		}
		meta.Source = source
	case *fhir.InsurancePlan:
		meta := resource.(*fhir.InsurancePlan).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.InsurancePlan).Meta = meta
		}
		meta.Source = source
	case *fhir.Invoice:
		meta := resource.(*fhir.Invoice).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Invoice).Meta = meta
		}
		meta.Source = source
	case *fhir.Library:
		meta := resource.(*fhir.Library).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Library).Meta = meta
		}
		meta.Source = source
	case *fhir.Linkage:
		meta := resource.(*fhir.Linkage).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Linkage).Meta = meta
		}
		meta.Source = source
	case *fhir.List:
		meta := resource.(*fhir.List).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.List).Meta = meta
		}
		meta.Source = source
	case *fhir.Location:
		meta := resource.(*fhir.Location).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Location).Meta = meta
		}
		meta.Source = source
	case *fhir.Measure:
		meta := resource.(*fhir.Measure).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Measure).Meta = meta
		}
		meta.Source = source
	case *fhir.MeasureReport:
		meta := resource.(*fhir.MeasureReport).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MeasureReport).Meta = meta
		}
		meta.Source = source
	case *fhir.Media:
		meta := resource.(*fhir.Media).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Media).Meta = meta
		}
		meta.Source = source
	case *fhir.Medication:
		meta := resource.(*fhir.Medication).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Medication).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicationAdministration:
		meta := resource.(*fhir.MedicationAdministration).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicationAdministration).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicationDispense:
		meta := resource.(*fhir.MedicationDispense).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicationDispense).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicationKnowledge:
		meta := resource.(*fhir.MedicationKnowledge).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicationKnowledge).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicationRequest:
		meta := resource.(*fhir.MedicationRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicationRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicationStatement:
		meta := resource.(*fhir.MedicationStatement).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicationStatement).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProduct:
		meta := resource.(*fhir.MedicinalProduct).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProduct).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductAuthorization:
		meta := resource.(*fhir.MedicinalProductAuthorization).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductAuthorization).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductContraindication:
		meta := resource.(*fhir.MedicinalProductContraindication).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductContraindication).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductIndication:
		meta := resource.(*fhir.MedicinalProductIndication).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductIndication).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductIngredient:
		meta := resource.(*fhir.MedicinalProductIngredient).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductIngredient).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductInteraction:
		meta := resource.(*fhir.MedicinalProductInteraction).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductInteraction).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductManufactured:
		meta := resource.(*fhir.MedicinalProductManufactured).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductManufactured).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductPackaged:
		meta := resource.(*fhir.MedicinalProductPackaged).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductPackaged).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductPharmaceutical:
		meta := resource.(*fhir.MedicinalProductPharmaceutical).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductPharmaceutical).Meta = meta
		}
		meta.Source = source
	case *fhir.MedicinalProductUndesirableEffect:
		meta := resource.(*fhir.MedicinalProductUndesirableEffect).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MedicinalProductUndesirableEffect).Meta = meta
		}
		meta.Source = source
	case *fhir.MessageDefinition:
		meta := resource.(*fhir.MessageDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MessageDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.MessageHeader:
		meta := resource.(*fhir.MessageHeader).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MessageHeader).Meta = meta
		}
		meta.Source = source
	case *fhir.MolecularSequence:
		meta := resource.(*fhir.MolecularSequence).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.MolecularSequence).Meta = meta
		}
		meta.Source = source
	case *fhir.NamingSystem:
		meta := resource.(*fhir.NamingSystem).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.NamingSystem).Meta = meta
		}
		meta.Source = source
	case *fhir.NutritionOrder:
		meta := resource.(*fhir.NutritionOrder).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.NutritionOrder).Meta = meta
		}
		meta.Source = source
	case *fhir.Observation:
		meta := resource.(*fhir.Observation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Observation).Meta = meta
		}
		meta.Source = source
	case *fhir.ObservationDefinition:
		meta := resource.(*fhir.ObservationDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ObservationDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.OperationDefinition:
		meta := resource.(*fhir.OperationDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.OperationDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.OperationOutcome:
		meta := resource.(*fhir.OperationOutcome).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.OperationOutcome).Meta = meta
		}
		meta.Source = source
	case *fhir.Organization:
		meta := resource.(*fhir.Organization).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Organization).Meta = meta
		}
		meta.Source = source
	case *fhir.OrganizationAffiliation:
		meta := resource.(*fhir.OrganizationAffiliation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.OrganizationAffiliation).Meta = meta
		}
		meta.Source = source
	case *fhir.Parameters:
		meta := resource.(*fhir.Parameters).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Parameters).Meta = meta
		}
		meta.Source = source
	case *fhir.Patient:
		meta := resource.(*fhir.Patient).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Patient).Meta = meta
		}
		meta.Source = source
	case *fhir.PaymentNotice:
		meta := resource.(*fhir.PaymentNotice).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.PaymentNotice).Meta = meta
		}
		meta.Source = source
	case *fhir.PaymentReconciliation:
		meta := resource.(*fhir.PaymentReconciliation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.PaymentReconciliation).Meta = meta
		}
		meta.Source = source
	case *fhir.Person:
		meta := resource.(*fhir.Person).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Person).Meta = meta
		}
		meta.Source = source
	case *fhir.PlanDefinition:
		meta := resource.(*fhir.PlanDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.PlanDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.Practitioner:
		meta := resource.(*fhir.Practitioner).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Practitioner).Meta = meta
		}
		meta.Source = source
	case *fhir.PractitionerRole:
		meta := resource.(*fhir.PractitionerRole).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.PractitionerRole).Meta = meta
		}
		meta.Source = source
	case *fhir.Procedure:
		meta := resource.(*fhir.Procedure).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Procedure).Meta = meta
		}
		meta.Source = source
	case *fhir.Provenance:
		meta := resource.(*fhir.Provenance).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Provenance).Meta = meta
		}
		meta.Source = source
	case *fhir.Questionnaire:
		meta := resource.(*fhir.Questionnaire).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Questionnaire).Meta = meta
		}
		meta.Source = source
	case *fhir.QuestionnaireResponse:
		meta := resource.(*fhir.QuestionnaireResponse).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.QuestionnaireResponse).Meta = meta
		}
		meta.Source = source
	case *fhir.RelatedPerson:
		meta := resource.(*fhir.RelatedPerson).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.RelatedPerson).Meta = meta
		}
		meta.Source = source
	case *fhir.RequestGroup:
		meta := resource.(*fhir.RequestGroup).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.RequestGroup).Meta = meta
		}
		meta.Source = source
	case *fhir.ResearchDefinition:
		meta := resource.(*fhir.ResearchDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ResearchDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.ResearchElementDefinition:
		meta := resource.(*fhir.ResearchElementDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ResearchElementDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.ResearchStudy:
		meta := resource.(*fhir.ResearchStudy).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ResearchStudy).Meta = meta
		}
		meta.Source = source
	case *fhir.ResearchSubject:
		meta := resource.(*fhir.ResearchSubject).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ResearchSubject).Meta = meta
		}
		meta.Source = source
	case *fhir.RiskAssessment:
		meta := resource.(*fhir.RiskAssessment).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.RiskAssessment).Meta = meta
		}
		meta.Source = source
	case *fhir.RiskEvidenceSynthesis:
		meta := resource.(*fhir.RiskEvidenceSynthesis).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.RiskEvidenceSynthesis).Meta = meta
		}
		meta.Source = source
	case *fhir.Schedule:
		meta := resource.(*fhir.Schedule).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Schedule).Meta = meta
		}
		meta.Source = source
	case *fhir.SearchParameter:
		meta := resource.(*fhir.SearchParameter).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SearchParameter).Meta = meta
		}
		meta.Source = source
	case *fhir.ServiceRequest:
		meta := resource.(*fhir.ServiceRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ServiceRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.Slot:
		meta := resource.(*fhir.Slot).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Slot).Meta = meta
		}
		meta.Source = source
	case *fhir.Specimen:
		meta := resource.(*fhir.Specimen).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Specimen).Meta = meta
		}
		meta.Source = source
	case *fhir.SpecimenDefinition:
		meta := resource.(*fhir.SpecimenDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SpecimenDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.StructureDefinition:
		meta := resource.(*fhir.StructureDefinition).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.StructureDefinition).Meta = meta
		}
		meta.Source = source
	case *fhir.StructureMap:
		meta := resource.(*fhir.StructureMap).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.StructureMap).Meta = meta
		}
		meta.Source = source
	case *fhir.Subscription:
		meta := resource.(*fhir.Subscription).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Subscription).Meta = meta
		}
		meta.Source = source
	case *fhir.Substance:
		meta := resource.(*fhir.Substance).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Substance).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstanceNucleicAcid:
		meta := resource.(*fhir.SubstanceNucleicAcid).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstanceNucleicAcid).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstancePolymer:
		meta := resource.(*fhir.SubstancePolymer).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstancePolymer).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstanceProtein:
		meta := resource.(*fhir.SubstanceProtein).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstanceProtein).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstanceReferenceInformation:
		meta := resource.(*fhir.SubstanceReferenceInformation).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstanceReferenceInformation).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstanceSourceMaterial:
		meta := resource.(*fhir.SubstanceSourceMaterial).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstanceSourceMaterial).Meta = meta
		}
		meta.Source = source
	case *fhir.SubstanceSpecification:
		meta := resource.(*fhir.SubstanceSpecification).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SubstanceSpecification).Meta = meta
		}
		meta.Source = source
	case *fhir.SupplyDelivery:
		meta := resource.(*fhir.SupplyDelivery).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SupplyDelivery).Meta = meta
		}
		meta.Source = source
	case *fhir.SupplyRequest:
		meta := resource.(*fhir.SupplyRequest).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.SupplyRequest).Meta = meta
		}
		meta.Source = source
	case *fhir.Task:
		meta := resource.(*fhir.Task).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.Task).Meta = meta
		}
		meta.Source = source
	case *fhir.TerminologyCapabilities:
		meta := resource.(*fhir.TerminologyCapabilities).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.TerminologyCapabilities).Meta = meta
		}
		meta.Source = source
	case *fhir.TestReport:
		meta := resource.(*fhir.TestReport).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.TestReport).Meta = meta
		}
		meta.Source = source
	case *fhir.TestScript:
		meta := resource.(*fhir.TestScript).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.TestScript).Meta = meta
		}
		meta.Source = source
	case *fhir.ValueSet:
		meta := resource.(*fhir.ValueSet).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.ValueSet).Meta = meta
		}
		meta.Source = source
	case *fhir.VerificationResult:
		meta := resource.(*fhir.VerificationResult).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.VerificationResult).Meta = meta
		}
		meta.Source = source
	case *fhir.VisionPrescription:
		meta := resource.(*fhir.VisionPrescription).Meta
		if meta == nil {
			meta = &fhir.Meta{}
			resource.(*fhir.VisionPrescription).Meta = meta
		}
		meta.Source = source
	default:
		panic("SetSource called with non-FHIR resource, or not a pointer: " + fmt.Sprintf("%T", resource))
	}
}

