services:
  application:
    image: leplusorg/openid-connect-provider-debugger
    ports:
      - "8081:80"
    environment:
      - oidc_client_id=test
    depends_on:
      orchestrator:
        condition: service_healthy
  orchestrator:
    #image: ghcr.io/santeonnl/orca_orchestrator:main
    build:
      context: ../../orchestrator
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ORCA_NUTS_API_URL=http://nutsnode:8081
      - ORCA_NUTS_PUBLIC_URL=http://nutsnode:8081
      - ORCA_NUTS_SUBJECT=fake
      - ORCA_NUTS_DISCOVERYSERVICE=fake
      - ORCA_PUBLIC_URL=http://localhost:8080
      - ORCA_STRICTMODE=false
      - ORCA_CAREPLANCONTRIBUTOR_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_FHIR_URL=http://fhirstore:5826/fhir/r4/
      - ORCA_CAREPLANCONTRIBUTOR_FRONTEND_URL=http://localhost:8081
      - ORCA_CAREPLANCONTRIBUTOR_APPLAUNCH_DEMO_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_CLIENTS_TEST_ID=test
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_CLIENTS_TEST_REDIRECT_URI=http://localhost:8081/callback
  fhirstore:
    image: ghcr.io/fhir/fhir-candle:latest
    ports:
      - "5826:5826"
