services:
  proxy:
    image: nginx:latest
    depends_on:
      - application
      - orchestrator
    volumes:
      - ./proxy.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "8080:8080"
  application:
    image: leplusorg/openid-connect-provider-debugger
    volumes:
      - ./application.conf:/etc/nginx/conf.d/default.conf:ro
  orchestrator:
    #image: ghcr.io/santeonnl/orca_orchestrator:main
    build:
      context: ../../orchestrator
      dockerfile: Dockerfile
    environment:
      - ORCA_NUTS_API_URL=http://nutsnode:8081
      - ORCA_NUTS_PUBLIC_URL=http://nutsnode:8081
      - ORCA_NUTS_SUBJECT=fake
      - ORCA_NUTS_DISCOVERYSERVICE=fake
      - ORCA_PUBLIC_URL=${URL}/orca
      - ORCA_STRICTMODE=false
      - ORCA_CAREPLANCONTRIBUTOR_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_FHIR_URL=http://fhirstore:5826/fhir/r4/
      - ORCA_CAREPLANCONTRIBUTOR_FRONTEND_URL=/
      - ORCA_CAREPLANCONTRIBUTOR_APPLAUNCH_DEMO_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_CLIENTS_TEST_ID=test
      - ORCA_CAREPLANCONTRIBUTOR_OIDC_CLIENTS_TEST_REDIRECTURI=${URL}/login
  fhirstore:
    image: ghcr.io/fhir/fhir-candle:latest
    ports:
      - "5826:5826"
