// Code generated by MockGen. DO NOT EDIT.
// Source: azure_oauth.go
//
// Generated by this command:
//
//	mockgen -destination=./azure_oauth_mock.go -package=ehr -source=azure_oauth.go
//

// Package ehr is a generated GoMock package.
package ehr

import (
	context "context"
	reflect "reflect"

	azcore "github.com/Azure/azure-sdk-for-go/sdk/azcore"
	azidentity "github.com/Azure/azure-sdk-for-go/sdk/azidentity"
	gomock "go.uber.org/mock/gomock"
)

// MockAzureOauthClient is a mock of AzureOauthClient interface.
type MockAzureOauthClient struct {
	ctrl     *gomock.Controller
	recorder *MockAzureOauthClientMockRecorder
	isgomock struct{}
}

// MockAzureOauthClientMockRecorder is the mock recorder for MockAzureOauthClient.
type MockAzureOauthClientMockRecorder struct {
	mock *MockAzureOauthClient
}

// NewMockAzureOauthClient creates a new mock instance.
func NewMockAzureOauthClient(ctrl *gomock.Controller) *MockAzureOauthClient {
	mock := &MockAzureOauthClient{ctrl: ctrl}
	mock.recorder = &MockAzureOauthClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAzureOauthClient) EXPECT() *MockAzureOauthClientMockRecorder {
	return m.recorder
}

// GetAzureCredential mocks base method.
func (m *MockAzureOauthClient) GetAzureCredential() (*azidentity.DefaultAzureCredential, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAzureCredential")
	ret0, _ := ret[0].(*azidentity.DefaultAzureCredential)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAzureCredential indicates an expected call of GetAzureCredential.
func (mr *MockAzureOauthClientMockRecorder) GetAzureCredential() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAzureCredential", reflect.TypeOf((*MockAzureOauthClient)(nil).GetAzureCredential))
}

// GetBearerToken mocks base method.
func (m *MockAzureOauthClient) GetBearerToken(context context.Context, spt azcore.TokenCredential, endpoint string) (*azcore.AccessToken, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBearerToken", context, spt, endpoint)
	ret0, _ := ret[0].(*azcore.AccessToken)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBearerToken indicates an expected call of GetBearerToken.
func (mr *MockAzureOauthClientMockRecorder) GetBearerToken(context, spt, endpoint any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBearerToken", reflect.TypeOf((*MockAzureOauthClient)(nil).GetBearerToken), context, spt, endpoint)
}
