{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "orca.fullname" . }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    {{ .Values.gateway.hosts | toYaml | nindent 4 }}
  rules:
    {{- if .Values.viewer.enabled }}
    - matches:
      - path:
          type: PathPrefix
          value: /viewer
      backendRefs:
        - name: {{ include "orca.fullname" . }}-viewer
          port: 3000
    {{- end }}
    {{- if .Values.frontend.enabled }}
    - matches:
      - path:
          type: PathPrefix
          value: /frontend
      backendRefs:
        - name: {{ include "orca.fullname" . }}-frontend
          port: 3000
    {{- end }}
    - matches:
      - path:
          type: PathPrefix
          value: /orca
      filters:
        - type: URLRewrite
          urlRewrite:
            path:
              type: ReplacePrefixMatch
              replacePrefixMatch: /
      backendRefs:
        - name: {{ include "orca.fullname" . }}
          port: {{ .Values.service.port }}
{{- end }}
