services:
  proxy:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - "./nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro"
  hospital_orchestrator:
    image: "${ORCHESTRATOR_IMAGE:-ghcr.io/santeonnl/orca_orchestrator:main}"
    environment:
      - ORCA_NUTS_API_ADDRESS=http://nutsnode:8081
      - ORCA_PUBLIC_BASEURL=/hospital/orca
      - ORCA_CAREPLANCONTRIBUTOR_ENABLED=true
      - ORCA_CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL=http://proxy:8080/clinic/orca/cps
      - ORCA_APPLAUNCH_DEMO_ENABLED=true
  clinic_orchestrator:
    image: "${ORCHESTRATOR_IMAGE:-ghcr.io/santeonnl/orca_orchestrator:main}"
    environment:
      - ORCA_NUTS_API_ADDRESS=http://nutsnode:8081
      - ORCA_CAREPLANSERVICE_ENABLED=true
      - ORCA_CAREPLANSERVICE_FHIR_URL=http://fhirstore:8080/fhir
    depends_on:
      - fhirstore
    healthcheck:
      interval: 3s
      timeout: 3s
      retries: 30
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://fhirstore:8080/fhir/Task"]
  fhirstore:
    image: hapiproject/hapi:v7.2.0
    ports:
      - "9090:8080"
    environment:
      - hapi.fhir.fhir_version=R4
