# syntax=docker/dockerfile:1
FROM node:24-alpine AS base

WORKDIR /app

ENV NEXT_PUBLIC_BASE_PATH /ehr

COPY package.json package-lock.json ./
RUN npm ci
COPY . .

EXPOSE 3000

CMD ["npm", "run", "dev"]