# SonarQube project configuration
sonar.organization=orca
sonar.projectKey=orca-hospital-simulator
sonar.projectName=ORCA Hospital Simulator
sonar.projectVersion=0.0.6

sonar.sources=app,public,utils
sonar.sourceEncoding=UTF-8
