services:
  proxy:
    image: nginx:latest
    depends_on:
      - nutsnode
      - orchestrator
    ports:
      - "7080:8080"
    volumes:
      - "./config/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro"
  nutsnode:
    image: nutsfoundation/nuts-node:6.1.0-alpha.1
    ports:
      - "8081:8081" # port exposed for loading test data (create DIDs and VCs, requesting access token)
    volumes:
      - "../shared_config/policy/:/nuts/config/policy:ro"
      - "../shared_config/discovery/homemonitoring.json:/nuts/discovery/homemonitoring.json:ro"
      - "../shared_config/truststore.pem:/nuts/config/truststore.pem:ro"
    environment:
      - NUTS_VERBOSITY=debug
      - NUTS_STRICTMODE=false
      - NUTS_VERBOSITY=debug
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
      - NUTS_URL=${NUTS_URL}
      - NUTS_DISCOVERY_DEFINITIONS_DIRECTORY=/nuts/discovery/
      - NUTS_TLS_TRUSTSTOREFILE=/nuts/config/truststore.pem
      - NUTS_DIDMETHODS=web
  nutsadmin:
    image: "nutsfoundation/nuts-admin:main"
    environment:
      - NUTS_NODE_ADDRESS=http://nutsnode:8081
    ports:
      - "1305:1305"
  orchestrator:
    image: ghcr.io/santeonnl/orca_orchestrator:main
    # build:
    #  context: ../../../orchestrator
    #  dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - ORCA_NUTS_API_URL=http://nutsnode:8081
      - ORCA_NUTS_PUBLIC_URL=${NUTS_URL}
      - ORCA_NUTS_SUBJECT=clinic
      - ORCA_NUTS_DISCOVERYSERVICE=dev:HomeMonitoring2024
      - ORCA_PUBLIC_URL=${NUTS_URL}/orca
      - ORCA_CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL=${CAREPLANCONTRIBUTOR_CAREPLANSERVICE_URL}
      - ORCA_CAREPLANCONTRIBUTOR_STATICBEARERTOKEN=valid
      - ORCA_CAREPLANCONTRIBUTOR_HEALTHDATAVIEWENDPOINTENABLED=true
  viewer:
    image: ghcr.io/santeonnl/orca_viewersimulator:main
    # build:
    #   context: ../../../viewer_simulator
    #   dockerfile: Dockerfile
    environment:
      FHIR_BASE_URL: http://orchestrator:8080/cpc/cps/fhir
      FHIR_AUTHORIZATION_TOKEN: valid
