services:
  proxy:
    image: nginx:latest
    depends_on:
      - nutsnode
      - orchestrator
    ports:
      - "7080:8080"
    volumes:
      - "./config/nginx-proxy.conf:/etc/nginx/conf.d/nginx-proxy.conf:ro"
  nutsnode:
    image: nutsfoundation/nuts-node:6.0.0-beta.3
    ports:
      - "8081:8081" # port exposed for loading test data (create DIDs and VCs, requesting access token)
    volumes:
      - "../shared_config/policy/:/nuts/config/policy:ro"
    environment:
      - NUTS_VERBOSITY=debug
      - NUTS_STRICTMODE=false
      - NUTS_HTTP_INTERNAL_ADDRESS=:8081
      - NUTS_AUTH_CONTRACTVALIDATORS=dummy
      - NUTS_URL=${CLINIC_URL}
  orchestrator:
    build:
      context: ../../../orchestrator
      dockerfile: Dockerfile
    ports:
      - "8080"
    environment:
      - ORCA_NUTS_API_ADDRESS=http://nutsnode:8081
  fhirstore:
    image: hapiproject/hapi:v7.2.0
    ports:
      - "7090:8080"
    environment:
      - hapi.fhir.fhir_version=R4