package careplanservice

import (
	"encoding/json"
	"fmt"
	fhirclient "github.com/SanteonNL/go-fhir-client"
	"github.com/SanteonNL/orca/orchestrator/lib/coolfhir"
	"github.com/SanteonNL/orca/orchestrator/lib/to"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"github.com/samply/golang-fhir-models/fhir-models/fhir"
	"net/http"
)

func (s *Service) handleCreateCarePlan(httpResponse http.ResponseWriter, httpRequest *http.Request) error {
	log.Info().Msg("Creating CarePlan")
	// TODO: Authorize request here
	// TODO: Check only allowed fields are set, or only the allowed values (INT-204)?
	var carePlan fhir.CarePlan
	if err := s.readRequest(httpRequest, &carePlan); err != nil {
		return fmt.Errorf("invalid %T: %w", carePlan, err)
	}
	// Reset CarePlan.Id to nil to ensure it is generated by the server
	carePlan.Id = nil

	careTeamURL := "urn:uuid:" + uuid.NewString()
	careTeam := fhir.CareTeam{}
	carePlan.CareTeam = append(carePlan.CareTeam, fhir.Reference{
		Reference: to.Ptr(careTeamURL),
		Type:      to.Ptr(coolfhir.ResourceType(careTeam)),
	})

	bundle := coolfhir.Transaction().
		Create(carePlan).
		Create(careTeam, coolfhir.WithFullUrl(careTeamURL)).
		Bundle()

	// TODO: Manage time-outs properly
	var resultBundle fhir.Bundle
	if err := s.fhirClient.Create(bundle, &resultBundle, fhirclient.AtPath("/")); err != nil {
		return fmt.Errorf("failed to create CarePlan and CareTeam: %w", err)
	}

	var result fhir.CarePlan
	headers := new(fhirclient.Headers)
	if err := s.fhirClient.Read(*resultBundle.Entry[0].Response.Location, &result, fhirclient.ResponseHeaders(headers)); err != nil {
		return fmt.Errorf("failed to read created CarePlan: %w", err)
	}
	for key, value := range headers.Header {
		httpResponse.Header()[key] = value
	}
	httpResponse.WriteHeader(http.StatusCreated)
	return json.NewEncoder(httpResponse).Encode(result)
}
