package careplanservice

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/SanteonNL/orca/orchestrator/lib/audit"
	"github.com/SanteonNL/orca/orchestrator/lib/auth"
	"github.com/SanteonNL/orca/orchestrator/lib/coolfhir"
	"github.com/SanteonNL/orca/orchestrator/lib/to"
	"github.com/google/uuid"
	"github.com/rs/zerolog/log"
	"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"
)

func (s *Service) handleCreateServiceRequest(ctx context.Context, request FHIRHandlerRequest, tx *coolfhir.BundleBuilder) (FHIRHandlerResult, error) {
	log.Ctx(ctx).Info().Msg("Creating ServiceRequest")
	var serviceRequest fhir.ServiceRequest
	if err := json.Unmarshal(request.ResourceData, &serviceRequest); err != nil {
		return nil, fmt.Errorf("invalid %T: %w", serviceRequest, coolfhir.BadRequestError(err))
	}

	// Check we're only allowing secure external literal references
	if err := s.validateLiteralReferences(ctx, &serviceRequest); err != nil {
		return nil, err
	}

	// ServiceRequest.id must be generated by the backing FHIR API, so it must be nil in the request
	serviceRequest.Id = nil

	// Get the current principal
	principal, err := auth.PrincipalFromContext(ctx)
	if err != nil {
		return nil, err
	}

	// Get local identity for audit
	localIdentity, err := s.getLocalIdentity()
	if err != nil {
		return nil, fmt.Errorf("failed to get local identity: %w", err)
	}

	// Verify the requester is the same as the local identity
	if !isRequesterLocalCareOrganization([]fhir.Organization{{Identifier: []fhir.Identifier{*localIdentity}}}, principal) {
		return nil, coolfhir.NewErrorWithCode("Only the local care organization can create a ServiceRequest", http.StatusForbidden)
	}

	// TODO: Field validation

	// Set requester to the current organization if not already set
	if serviceRequest.Requester == nil {
		serviceRequest.Requester = &fhir.Reference{
			Identifier: &principal.Organization.Identifier[0],
			Type:       to.Ptr("Organization"),
		}
	} else if !coolfhir.ValidateReference(*serviceRequest.Requester) {
		return nil, coolfhir.NewErrorWithCode("ServiceRequest.requester must be a valid reference", http.StatusBadRequest)
	}

	serviceRequestBundleEntry := request.bundleEntryWithResource(serviceRequest)
	if serviceRequestBundleEntry.FullUrl == nil {
		serviceRequestBundleEntry.FullUrl = to.Ptr("urn:uuid:" + uuid.NewString())
	}

	// Create audit event for the creation
	createAuditEvent := audit.Event(*localIdentity, fhir.AuditEventActionC,
		&fhir.Reference{
			Reference: serviceRequestBundleEntry.FullUrl,
			Type:      to.Ptr("ServiceRequest"),
		},
		&fhir.Reference{
			Identifier: &principal.Organization.Identifier[0],
			Type:       to.Ptr("Organization"),
		},
	)

	// Add to transaction
	tx.Create(serviceRequest, coolfhir.WithFullUrl(*serviceRequestBundleEntry.FullUrl))
	serviceRequestEntryIdx := len(tx.Entry) - 1
	tx.Create(createAuditEvent)

	return func(txResult *fhir.Bundle) (*fhir.BundleEntry, []any, error) {
		var createdServiceRequest fhir.ServiceRequest
		result, err := coolfhir.NormalizeTransactionBundleResponseEntry(ctx, s.fhirClient, s.fhirURL, &tx.Entry[serviceRequestEntryIdx], &txResult.Entry[serviceRequestEntryIdx], &createdServiceRequest)
		if err != nil {
			return nil, nil, fmt.Errorf("failed to process ServiceRequest creation result: %w", err)
		}

		return result, []any{&createdServiceRequest}, nil
	}, nil
}
