package careplanservice

import (
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"github.com/SanteonNL/orca/orchestrator/lib/debug"
	"github.com/SanteonNL/orca/orchestrator/lib/otel"
	"net/http"
	"strings"

	fhirclient "github.com/SanteonNL/go-fhir-client"
	"github.com/SanteonNL/orca/orchestrator/lib/auth"
	"github.com/google/uuid"
	"go.opentelemetry.io/otel/attribute"
	"go.opentelemetry.io/otel/codes"
	"go.opentelemetry.io/otel/trace"

	"github.com/SanteonNL/orca/orchestrator/careplanservice/careteamservice"
	"github.com/SanteonNL/orca/orchestrator/lib/coolfhir"
	"github.com/SanteonNL/orca/orchestrator/lib/to"
	"github.com/rs/zerolog/log"
	"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"
)

func (s *Service) handleCreateTask(ctx context.Context, request FHIRHandlerRequest, tx *coolfhir.BundleBuilder) (FHIRHandlerResult, error) {
	ctx, span := tracer.Start(
		ctx,
		debug.GetFullCallerName(),
		trace.WithSpanKind(trace.SpanKindServer),
		trace.WithAttributes(
			attribute.String(otel.FHIRResourceType, "Task"),
		),
	)
	defer span.End()

	log.Ctx(ctx).Info().Msg("Creating Task")
	var task fhir.Task
	if err := json.Unmarshal(request.ResourceData, &task); err != nil {
		return nil, otel.Error(span, fmt.Errorf("invalid %T: %w", task, coolfhir.BadRequestError(err)), "failed to unmarshal task")
	}

	// Task is owned by CPS, don't allow changing or setting the source of the Task
	if task.Meta != nil {
		task.Meta.Source = nil
	}

	// Check we're only allowing secure external literal references
	if err := validateLiteralReferences(ctx, s.profile, &task); err != nil {
		return nil, otel.Error(span, err, "literal reference validation failed")
	}

	// Task.id must be generated by the backing FHIR API, so it must be nil in the request
	task.Id = nil

	if !coolfhir.IsScpTask(&task) {
		return nil, otel.Error(span, coolfhir.NewErrorWithCode("Task is not SCP task", http.StatusBadRequest), "task is not SCP task")
	}

	switch task.Status {
	case fhir.TaskStatusRequested:
	case fhir.TaskStatusReady:
	default:
		return nil, otel.Error(span, fmt.Errorf("cannot create Task with status %s, must be %s or %s", task.Status, fhir.TaskStatusRequested.String(), fhir.TaskStatusReady.String()), "invalid task status")
	}

	carePlan := fhir.CarePlan{}
	err := coolfhir.ValidateTaskRequiredFields(task)
	if err != nil {
		return nil, otel.Error(span, err, "task validation failed")
	}

	if !isPrincipalTaskRequester(&task, request.Principal) {
		return nil, otel.Error(span, coolfhir.BadRequest("requester must be equal to Task.requester"), "principal is not task requester")
	}

	// Enrich Task.Requester and Task.Owner with info from CSD (if available), typically to add the organization name
	// TODO: CSD is queried again later, to get the notification endpoint. We should optimize/cache this. Maybe in the context.Context?
	if entity, err := s.profile.CsdDirectory().LookupEntity(ctx, *task.Requester.Identifier); err != nil {
		log.Ctx(ctx).Info().Err(err).Msgf("Unable to lookup Task.requester in CSD, won't be enriched.")
	} else {
		task.Requester = entity
	}
	if entity, err := s.profile.CsdDirectory().LookupEntity(ctx, *task.Owner.Identifier); err != nil {
		log.Ctx(ctx).Info().Err(err).Msgf("Unable to lookup Task.owner in CSD, won't be enriched.")
	} else {
		task.Owner = entity
	}

	// Resolve the CarePlan
	var (
		taskEntryIdx           = -1
		taskBundleEntry        fhir.BundleEntry
		carePlanBundleEntryIdx = -1
		carePlanBundleEntry    *fhir.BundleEntry
	)

	fhirClient := s.fhirClientByTenant[request.Tenant.ID]
	if task.BasedOn == nil || len(task.BasedOn) == 0 {
		// The CarePlan does not exist, a CarePlan and CareTeam will be created and the requester will be added as a member
		span.AddEvent("creating_new_careplan_and_careteam")
		span.SetAttributes(attribute.String("fhir.careplan.creation_mode", "new"))

		// In order to create a CarePlan, the requester must have the same URA number as the current node
		ids, err := s.profile.Identities(ctx)
		if err != nil {
			return nil, otel.Error(span, err, "failed to get profile identities")
		}
		if !isRequesterLocalCareOrganization(ids, *request.Principal) {
			return nil, otel.Error(span, errors.New("requester must be local care organization in order to create new CarePlan and CareTeam"), "requester is not local care organization")
		}

		// Create a new CarePlan (which will also create a new CareTeam) based on the Task reference
		carePlanURL := "urn:uuid:" + uuid.NewString()
		careTeamID := "cps-careteam"
		taskURL := "urn:uuid:" + uuid.NewString()
		careTeam := fhir.CareTeam{Id: to.Ptr(careTeamID)}
		carePlan.CareTeam = append(carePlan.CareTeam, fhir.Reference{
			Reference: to.Ptr("#" + careTeamID),
			Type:      to.Ptr(coolfhir.ResourceType(careTeam)),
		})
		carePlan.Intent = fhir.CarePlanIntentOrder
		carePlan.Activity = append(carePlan.Activity, fhir.CarePlanActivity{
			Reference: &fhir.Reference{
				Reference: to.Ptr(taskURL),
				Type:      to.Ptr(coolfhir.ResourceType(task)),
			},
		})
		carePlan.Category = []fhir.CodeableConcept{
			{
				Coding: []fhir.Coding{
					{
						System:  to.Ptr("http://snomed.info/sct"),
						Code:    to.Ptr("135411000146103"),
						Display: to.Ptr("Multidisciplinary care regime"),
					},
				},
			},
		}

		// Validate Task.For: identifier (with system and value), and/or reference must be set
		if task.For == nil || !coolfhir.ValidateReference(*task.For) {
			return nil, otel.Error(span, coolfhir.NewErrorWithCode("Task.For must be set with a local reference, or a logical identifier, referencing a patient", http.StatusBadRequest), "invalid task.for reference")
		}
		if task.For.Reference == nil {
			headers := fhirclient.Headers{}
			patients, _, err := handleSearchResource[fhir.Patient](ctx, fhirClient, "Patient", map[string][]string{"identifier": {fmt.Sprintf("%s|%s", *task.For.Identifier.System, *task.For.Identifier.Value)}}, &headers)
			if err != nil {
				return nil, otel.Error(span, err, "failed to search for patient")
			}

			if len(patients) == 0 {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("Task.For must be set with a local reference, or a logical identifier, referencing an existing patient", http.StatusNotFound), "patient not found")
			} else {
				task.For.Reference = to.Ptr("Patient/" + *patients[0].Id)
			}
		}

		span.AddEvent("activating_careteam_membership")
		ok := careteamservice.ActivateMembership(ctx, &careTeam, task.Requester)
		if !ok {
			return nil, otel.Error(span, errors.New("failed to activate membership for new CareTeam"), "failed to activate care team membership")
		}

		data, err := json.Marshal([]any{careTeam})
		if err != nil {
			return nil, otel.Error(span, coolfhir.NewErrorWithCode("failed to marshal CareTeam", http.StatusInternalServerError), "failed to marshal care team")
		}

		carePlan.Subject = *task.For
		carePlan.Status = fhir.RequestStatusActive
		carePlan.Author = task.Requester
		carePlan.Contained = data
		// This is technically not needed, but adding it for the sake of data consistency
		carePlan.Extension = []fhir.Extension{
			{
				Url: CreatorExtensionURL,
				ValueReference: &fhir.Reference{
					Type:       to.Ptr("Organization"),
					Identifier: task.Requester.Identifier,
				},
			},
		}

		task.BasedOn = []fhir.Reference{
			{
				Type:      to.Ptr(coolfhir.ResourceType(carePlan)),
				Reference: to.Ptr(carePlanURL),
			},
		}
		task.Extension = []fhir.Extension{
			{
				Url: CreatorExtensionURL,
				ValueReference: &fhir.Reference{
					Type:       to.Ptr("Organization"),
					Identifier: task.Requester.Identifier,
				},
			},
		}

		span.AddEvent("adding_careplan_and_task_to_transaction_bundle")
		carePlanBundleEntryIdx = len(tx.Entry)
		tx.Create(carePlan, coolfhir.WithFullUrl(carePlanURL), coolfhir.WithAuditEvent(ctx, tx, coolfhir.AuditEventInfo{
			ActingAgent: &fhir.Reference{
				Identifier: task.Requester.Identifier,
				Type:       to.Ptr("Organization"),
			},
			Observer: *request.LocalIdentity,
			Action:   fhir.AuditEventActionC,
		}))
		carePlanBundleEntry = &tx.Entry[carePlanBundleEntryIdx]

		taskEntryIdx = len(tx.Entry)
		tx.Create(task, coolfhir.WithFullUrl(taskURL), coolfhir.WithRequestHeaders(request.HttpHeaders), coolfhir.WithAuditEvent(ctx, tx, coolfhir.AuditEventInfo{
			ActingAgent: &fhir.Reference{
				Identifier: task.Requester.Identifier,
				Type:       to.Ptr("Organization"),
			},
			Observer: *request.LocalIdentity,
			Action:   fhir.AuditEventActionC,
		}))
		taskBundleEntry = tx.Entry[taskEntryIdx]

		span.AddEvent("notifying_careplan_created_event")
		if s.eventManager.HasSubscribers(CarePlanCreatedEvent{}) {
			if err := s.eventManager.Notify(ctx, CarePlanCreatedEvent{
				CarePlan: carePlan,
			}); err != nil {
				return nil, otel.Error(span, err, "failed to notify care plan created event")
			}
		}
	} else {
		// Adding a task to an existing CarePlan
		span.AddEvent("adding_task_to_existing_careplan")
		span.SetAttributes(attribute.String("fhir.careplan.creation_mode", "existing"))

		carePlanRef, err := basedOn(task)
		if err != nil {
			return nil, otel.Error(span, fmt.Errorf("invalid Task.basedOn: %w", err), "invalid task.basedOn")
		}

		var carePlan fhir.CarePlan
		if err := fhirClient.ReadWithContext(ctx, *carePlanRef, &carePlan); err != nil {
			return nil, otel.Error(span, fmt.Errorf("failed to read CarePlan: %w", err), "failed to read care plan")
		}

		if task.For == nil {
			return nil, otel.Error(span, coolfhir.NewErrorWithCode("Task.For must be set with a local reference, or a logical identifier, referencing a patient", http.StatusBadRequest), "task.for is required")
		}

		task.Extension = []fhir.Extension{
			{
				Url: CreatorExtensionURL,
				ValueReference: &fhir.Reference{
					Type:       to.Ptr("Organization"),
					Identifier: task.Requester.Identifier,
				},
			},
		}

		span.AddEvent("validating_patient_consistency")
		samePatient := false
		// If either task.For or CarePlan.Subject contains an identifier, they must be equal
		// If neither contain an identifier, the reference must be equal
		if task.For.Identifier != nil || carePlan.Subject.Identifier != nil {
			samePatient = coolfhir.LogicalReferenceEquals(*task.For, carePlan.Subject)
		} else {
			samePatient = coolfhir.ReferenceValueEquals(*task.For, carePlan.Subject)
		}

		if !samePatient {
			return nil, otel.Error(span, coolfhir.NewErrorWithCode("Task.for must reference the same patient as CarePlan.subject", http.StatusBadRequest), "task.for does not match careplan.subject")
		}

		// Different validation logic for an SCP subtask
		if len(task.PartOf) > 0 {
			span.AddEvent("processing_scp_subtask")
			span.SetAttributes(attribute.String(otel.FHIRTaskType, "subtask"))

			if len(task.PartOf) != 1 {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("SCP subtask must have exactly one parent task", http.StatusBadRequest), "subtask must have exactly one parent")
			}
			// Get the parent task
			var parentTask fhir.Task
			err = fhirClient.ReadWithContext(ctx, *task.PartOf[0].Reference, &parentTask)
			if err != nil {
				return nil, otel.Error(span, err, "failed to read parent task")
			}
			// Verify the owner of the parent task is the same as the org creating the subtask
			isOwner, _ := coolfhir.IsIdentifierTaskOwnerAndRequester(&parentTask, request.Principal.Organization.Identifier)
			if !isOwner {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("requester is not the owner of the parent task", http.StatusUnauthorized), "requester is not parent task owner")
			}

			if !coolfhir.LogicalReferenceEquals(*parentTask.Owner, *task.Requester) {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("requester is not the same as the parent task owner", http.StatusBadRequest), "requester mismatch with parent task owner")
			}
			if !coolfhir.LogicalReferenceEquals(*parentTask.Requester, *task.Owner) {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("owner is not the same as the parent task requester", http.StatusBadRequest), "owner mismatch with parent task requester")
			}
		} else {
			span.AddEvent("processing_primary_task")
			span.SetAttributes(attribute.String(otel.FHIRTaskType, "primary"))

			careTeam, err := coolfhir.CareTeamFromCarePlan(&carePlan)
			if err != nil {
				return nil, otel.Error(span, fmt.Errorf("failed to parse CareTeam in CarePlan.Contained: %w", err), "failed to parse care team from care plan")
			}

			participant := coolfhir.FindMatchingParticipantInCareTeam(careTeam, request.Principal.Organization.Identifier)
			if participant == nil {
				return nil, otel.Error(span, coolfhir.NewErrorWithCode("requester is not part of CareTeam", http.StatusUnauthorized), "requester not in care team")
			}
		}

		// TODO: Manage time-outs properly
		// Add Task to CarePlan.activities
		taskBundleEntry = request.bundleEntryWithResource(task)
		if taskBundleEntry.FullUrl == nil {
			taskBundleEntry.FullUrl = to.Ptr("urn:uuid:" + uuid.NewString())
		}

		taskEntryIdx = len(tx.Entry)
		// TODO: Only if not updated
		tx.AppendEntry(taskBundleEntry, coolfhir.WithAuditEvent(ctx, tx, coolfhir.AuditEventInfo{
			ActingAgent: &fhir.Reference{
				Identifier: task.Requester.Identifier,
				Type:       to.Ptr("Organization"),
			},
			Observer: *request.LocalIdentity,
			Action:   fhir.AuditEventActionC,
		}))

		if len(task.PartOf) == 0 {
			span.AddEvent("updating_careplan_activities")
			// Don't add subtasks to CarePlan.activity
			carePlan.Activity = append(carePlan.Activity, fhir.CarePlanActivity{
				Reference: &fhir.Reference{
					Reference: taskBundleEntry.FullUrl,
					Type:      to.Ptr("Task"),
				},
			})

			updated, err := careteamservice.Update(ctx, fhirClient, *carePlan.Id, task, request.LocalIdentity, tx)
			if err != nil {
				return nil, otel.Error(span, fmt.Errorf("failed to update CareTeam: %w", err), "failed to update care team")
			}

			carePlanBundleEntryIdx = len(tx.Entry)
			if !updated {
				span.AddEvent("add_careplan_update_to_transaction")
				tx.Update(carePlan, "CarePlan/"+*carePlan.Id, coolfhir.WithAuditEvent(ctx, tx, coolfhir.AuditEventInfo{
					ActingAgent: &fhir.Reference{
						Identifier: task.Requester.Identifier,
						Type:       to.Ptr("Organization"),
					},
					Observer: *request.LocalIdentity,
					Action:   fhir.AuditEventActionU,
				}))
			}
			carePlanBundleEntry = &tx.Entry[carePlanBundleEntryIdx]
		}
	}

	span.SetStatus(codes.Ok, "")
	span.SetAttributes(attribute.String("fhir.task.creation", "success"))

	return func(txResult *fhir.Bundle) ([]*fhir.BundleEntry, []any, error) {
		var result *fhir.BundleEntry
		var notifications []any

		// Task
		{
			var createdTask fhir.Task
			var err error
			result, err = coolfhir.NormalizeTransactionBundleResponseEntry(ctx, fhirClient, request.BaseURL, &taskBundleEntry, &txResult.Entry[taskEntryIdx], &createdTask)
			if err != nil {
				return nil, nil, err
			}
			notifications = append(notifications, &createdTask)
		}

		// If CarePlan was updated/created, notify about CarePlan
		if carePlanBundleEntry != nil {
			var createdCarePlan fhir.CarePlan
			_, err = coolfhir.NormalizeTransactionBundleResponseEntry(ctx, fhirClient, request.BaseURL, carePlanBundleEntry, &txResult.Entry[carePlanBundleEntryIdx], &createdCarePlan)
			if err != nil {
				return nil, nil, err
			}
			notifications = append(notifications, &createdCarePlan)
		}

		return []*fhir.BundleEntry{result}, notifications, nil
	}, nil
}

// basedOn returns the CarePlan reference the Task is based on, e.g. CarePlan/123.
func basedOn(task fhir.Task) (*string, error) {
	if len(task.BasedOn) != 1 {
		return nil, errors.New("Task.basedOn must have exactly one reference")
	} else if task.BasedOn[0].Reference == nil || !strings.HasPrefix(*task.BasedOn[0].Reference, "CarePlan/") {
		return nil, errors.New("Task.basedOn must contain a relative reference to a CarePlan")
	}
	return task.BasedOn[0].Reference, nil
}

func isRequesterLocalCareOrganization(localIdentities []fhir.Organization, principal auth.Principal) bool {
	for _, localIdentity := range localIdentities {
		for _, requesterIdentifier := range principal.Organization.Identifier {
			for _, localIdentifier := range localIdentity.Identifier {
				if coolfhir.IdentifierEquals(&localIdentifier, &requesterIdentifier) {
					return true
				}
			}
		}
	}
	return false
}

func isPrincipalTaskRequester(task *fhir.Task, principal *auth.Principal) bool {
	if task.Requester == nil || task.Requester.Identifier == nil {
		return false
	}
	for _, identifier := range principal.Organization.Identifier {
		if coolfhir.IdentifierEquals(task.Requester.Identifier, &identifier) {
			return true
		}
	}
	return false
}
