@startuml orca-authenticate


actor "practitioner Charlie" as user order 10

participant "Viewer APP" as viewer order 20
participant "IDP zorgverlener" as idp order 30

entity "Identity Token" as id_token order 35

participant "orca-orchestrator-A" as orcaA order 40
participant "orca-NUTS-A" as nutsA order 50

group prelude
    user -> viewer: open
    activate viewer
    viewer --> user: redirect (302), location = idp
    user -> idp: login
    activate idp
    idp --> user: redirect (302), location = viewer?code=x
    user -> viewer: GET viewer?code=x
    viewer -> idp: GET /token?code=x
    idp -> id_token **: create
    idp --> viewer: access_token,id_token
    deactivate idp
end

group authenticate
    user -> viewer: request data
    viewer -> orcaA: GET .well-known/openid-configuration
    activate orcaA
    orcaA --> viewer: metadata
    deactivate orcaA
    viewer -> viewer: extract endpoints
    viewer -> id_token: get
    viewer -> user: redirect (302), location = /authenticate?id_token_hint=id_token
    user -> orcaA: GET /authenticate?id_token_hint=id_token
    activate orcaA
    orcaA -> id_token: validate
    orcaA -> user: redirect (302), location = viewer?code=x
    deactivate orcaA
    user -> viewer: GET viewer?code=x
    viewer -> orcaA: /token?code=x
    activate orcaA
    orcaA -> nutsA: create EmployeeCredential
    nutsA -> id_token: include
    nutsA --> orcaA: EmployeeCredential
    orcaA --> viewer: access_token,id_token
    deactivate orcaA
end

group access
    viewer -> orcaA: access data (access_token)
    orcaA -> orcaA: fetch data with EmployeeCredential
    orcaA --> viewer: data
    deactivate viewer
end

@enduml
