package main

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestMainExecution tests that main() executes successfully and generates the file
func TestMainExecution(t *testing.T) {
	// Create a temporary directory for the test
	tmpDir := t.TempDir()
	originalDir, err := os.Getwd()
	require.NoError(t, err)

	// Change to temp directory
	err = os.Chdir(tmpDir)
	require.NoError(t, err)
	defer os.Chdir(originalDir)

	// Run main()
	main()

	// Verify the file was created
	generatedFile := filepath.Join(tmpDir, "type.gen.go")
	_, err = os.Stat(generatedFile)
	assert.NoError(t, err, "Generated file should exist")

	// Read the generated file
	content, err := os.ReadFile(generatedFile)
	require.NoError(t, err)

	generatedCode := string(content)

	// Verify package declaration
	assert.Contains(t, generatedCode, "package coolfhir")

	// Verify generation comment
	assert.Contains(t, generatedCode, "// Code generated by go generate; DO NOT EDIT.")

	// Verify imports
	assert.Contains(t, generatedCode, `"fmt"`)
	assert.Contains(t, generatedCode, `"github.com/zorgbijjou/golang-fhir-models/fhir-models/fhir"`)

	// Verify all three functions exist
	assert.Contains(t, generatedCode, "func ResourceType(resource interface{}) string {")
	assert.Contains(t, generatedCode, "func ResourceID(resource interface{}) *string {")
	assert.Contains(t, generatedCode, "func SetSource(resource interface{}, source *string) {")
}
